/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * An anchor is a reference to an element in the UI.
 */
export type Anchor =
  | "bottom"
  | "bottom_left"
  | "bottom_right"
  | "bottom_middle"
  | "center"
  | "left"
  | "left_middle"
  | "right"
  | "right_middle"
  | "top"
  | "top_left"
  | "top_right"
  | "top_middle";
