/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A variable is a reference to a value that can be used in the UI.
 */
export interface VariableDefinition {
  [k: string]: unknown;
}
