/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Maximum number of particles that can be active at once for this emitter, evaluated once per particle emitter loop.
 */
export type MaximumParticles = string | number;
/**
 * How often a particle is emitted, in particles/sec evaluated once per particle emitted.
 */
export type SpawnRate = string | number;

/**
 * UNDOCUMENTED.
 */
export interface EmitterRateSteadyComponentFor1100 {
  max_particles?: MaximumParticles;
  spawn_rate?: SpawnRate;
}
