/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Evaluated once per particle emitted.
 */
export type MaximumParticles = string | number;

/**
 * UNDOCUMENTED.
 */
export interface EmitterRateManualComponentFor1100 {
  max_particles?: MaximumParticles;
}
