/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This is run once at emitter startup.
 */
export type CreationExpression = string;
/**
 * This is run once per emitter update.
 */
export type PerUpdateExpression = string;

/**
 * This component allows the emitter to run some Molang at creation, primarily to populate any Molang variables that get used later.
 */
export interface EmitterInitializationComponentFor1100 {
  creation_expression?: CreationExpression;
  per_update_expression?: PerUpdateExpression;
}
