/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * When the expression is non-zero, the emitter will emit particles. Evaluated every frame
 */
export type ActivationExpression = string | number;
/**
 * Emitter will expire if the expression is non-zero. Evaluated every frame
 */
export type ExpirationExpression = string | number;

/**
 * UNDOCUMENTED.
 */
export interface EmitterRateManualComponent1100 {
  activation_expression?: ActivationExpression;
  expiration_expression?: ExpirationExpression;
}
