/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Emitter will emit particles for this time per loop evaluated once per particle emitter loop.
 */
export type ActiveTime = string | number;
/**
 * Emitter will pause emitting particles for this time per loop evaluated once per particle emitter loop.
 */
export type SleepTime = string | number;

/**
 * UNDOCUMENTED.
 */
export interface EmitterLifetimeLoopingComponentFor1100 {
  active_time?: ActiveTime;
  sleep_time?: SleepTime;
}
