/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * How long the particles emit for evaluated once.
 */
export type ActiveTime = string | number;

/**
 * UNDOCUMENTED.
 */
export interface EmitterLifetimeOnceComponentFor1100 {
  active_time?: ActiveTime;
}
