/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This many particles are emitted at once evaluated once per particle emitter loop.
 */
export type NumParticles = string | number;

/**
 * UNDOCUMENTED.
 */
export interface EmitterRateInstantComponentFor1100 {
  num_particles?: NumParticles;
}
