/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The linear acceleration applied to the particle. Units are blocks/sec/sec
 *
 * @minItems 3
 * @maxItems 3
 */
export type LinearAcceleration = [MolangNumber, MolangNumber, MolangNumber];
/**
 * The minecraft molang definition that results in a float.
 */
export type MolangNumber = string | number;
/**
 * The minecraft molang definition that results in a float.
 */
export type MolangNumber1 = string | number;
/**
 * The minecraft molang definition that results in a float.
 */
export type MolangNumber2 = string | number;
/**
 * The minecraft molang definition that results in a float.
 */
export type MolangNumber3 = string | number;

/**
 * This component specifies the dynamic properties of the particle, from a simulation standpoint what forces act upon the particle? These dynamics alter the velocity of the particle, which is a combination of the direction of the particle and the speed. Particle direction will always be in the direction of the velocity of the particle.
 */
export interface ParticleMotionDynamicComponentFor1100 {
  linear_acceleration?: LinearAcceleration;
  linear_drag_coefficient?: MolangNumber1;
  rotation_acceleration?: MolangNumber2;
  rotation_drag_coefficient?: MolangNumber3;
}
