/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This expression makes the particle expire when true (non-zero), The float/expr is evaluated once per particle, evaluated every frame.
 */
export type ExpirationExpression = string | number;
/**
 * Alternate way to express lifetime, particle will expire after this much time, evaluated once.
 */
export type MaximumLifetime = string | number;

/**
 * UNDOCUMENTED:.
 */
export interface ParticleLifetimeExpressionComponentFor1100 {
  expiration_expression?: ExpirationExpression;
  max_lifetime?: MaximumLifetime;
}
