/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * UNDOCUMENTED: relative position.
 *
 * @minItems 3
 * @maxItems 3
 */
export type RelativePosition = [RelativePosition1, RelativePosition1, RelativePosition1];
/**
 * UNDOCUMENTED: relative position.
 */
export type RelativePosition1 = string | number;
/**
 * UNDOCUMENTED: rotation.
 */
export type Rotation = string | number;
/**
 * UNDOCUMENTED: relative position.
 *
 * @minItems 3
 * @maxItems 3
 */
export type Direction = [Direction1, Direction1, Direction1];
/**
 * UNDOCUMENTED: relative position.
 */
export type Direction1 = string | number;

/**
 * UNDOCUMENTED.
 */
export interface ParticleMotionParametricComponentFor1100 {
  relative_position?: RelativePosition;
  rotation?: Rotation;
  direction?: Direction;
}
