/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * How much protection does the armor item have.
 */
export type Protection = number;
/**
 * Texture Type to apply for the armor. Note that Horse armor is restricted to leather, iron, gold, or diamond.
 */
export type TextureType =
  | "gold"
  | "none"
  | "leather"
  | "chain"
  | "iron"
  | "diamond"
  | "elytra"
  | "turtle"
  | "netherite";

/**
 * The armor item component determines the amount of protection you have in your armor item.
 */
export interface Armor {
  protection: Protection;
  texture_type: TextureType;
}
