/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The minimum.
 */
export type Min = number;
/**
 * The maximum.
 */
export type Max = number;
/**
 * Maximum durability is the amount of damage that this item can take before breaking.
 */
export type MaximumDurability = number;

/**
 * Durability item component: how much damage can this item take before breaking.
 */
export interface Durability {
  damage_chance: DamageChance;
  max_durability?: MaximumDurability;
}
/**
 * Damage chance.
 */
export interface DamageChance {
  min: Min;
  max: Max;
}
