/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * If true you can always eat this item (even when not hungry), defaults to false.
 */
export type CanAlwaysEat = boolean;
/**
 * How much nutrition does this food item give the player when eaten.
 */
export type Nutrition = number;
/**
 * UNDOCUMENTED.
 */
export type Event = string;
/**
 * UNDOCUMENTED.
 */
export type Target = "self";
/**
 * If true, this food item is considered meat.
 */
export type IsMeat = boolean;

/**
 * When an item has a food component, it becomes edible to the player.
 */
export interface Food {
  can_always_eat?: CanAlwaysEat;
  nutrition?: Nutrition;
  on_consume?: OnConsume;
  is_meat?: IsMeat;
}
/**
 * UNDOCUMENTED.
 */
export interface OnConsume {
  event?: Event;
  target?: Target;
}
