/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * An index or expression for which frame of the icon to display. Default resolves to 0.
 */
export type Frame = Frame1 & Frame2;
export type Frame1 = number;
export type Frame2 = string;
/**
 * Legacy texture id for older item icons.
 */
export type Texture = string;
/**
 * The key from the resource_pack/textures/item_texture.json `texture_data` object associated with the texture file Example: blaze_powder.
 */
export type Texture1 = string;

/**
 * The icon item componenent determines the icon to represent the item in the UI and elsewhere.
 */
export interface Icon {
  frame?: Frame;
  legacy_id?: Texture;
  texture: Texture1;
}
