/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Event trigger for when the item is used.
 */
export type Event = string;
/**
 * Event target (block).
 */
export type Target = "block";

/**
 * The on_use_on item component allows you to receive an event when the item is used on a block in the world.
 */
export interface OnUseOn {
  on_use_on: OnUseOn1;
}
/**
 * Event trigger for when the item is used.
 */
export interface OnUseOn1 {
  event?: Event;
  target?: Target;
}
