/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Event trigger for when the item is used.
 */
export type Event = string;
/**
 * Event Target.
 */
export type Target = "self";

/**
 * The on_use item component allows you to receive an event when the item is used.
 */
export interface OnUse {
  on_use: OnUse1;
}
/**
 * Event trigger for when the item is used.
 */
export interface OnUse1 {
  event?: Event;
  target?: Target;
}
