/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Right hand transform data.
 */
export type MainHand = string;
/**
 * Left hand transform data.
 */
export type OffHand = string;

/**
 * Render offsets component: optional values can be given to offset the way the item is rendered. Depreciated in json formats 1.20.10 and higher
 */
export interface RenderOffsets {
  main_hand?: MainHand;
  off_hand?: OffHand;
}
