/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Whether the item should use the swing animation when thrown. Default is set to false.
 */
export type DoSwingAnimation = boolean;
/**
 * The scale at which the power of the throw increases. Default is set to 1.0.
 */
export type LaunchPowerScale = number;
/**
 * The maximum duration to draw a throwable item. Default is set to 0.0.
 */
export type MaximumDrawDuration = number;
/**
 * The minimum duration to draw a throwable item. Default is set to 0.0.
 */
export type MinimumDrawDuration = number;
/**
 * The maximum power to launch the throwable item. Default is set to 1.0.
 */
export type MaximumLaunchPower = number;
/**
 * Whether or not the power of the throw increases with duration charged. Default is set to false.
 */
export type ScalePowerByDrawDuration = boolean;

/**
 * Throwable item component. Throwable items, such as a snowball.
 */
export interface Throwable {
  do_swing_animation?: DoSwingAnimation;
  launch_power_scale?: LaunchPowerScale;
  max_draw_duration?: MaximumDrawDuration;
  min_draw_duration?: MinimumDrawDuration;
  max_launch_power?: MaximumLaunchPower;
  scale_power_by_draw_duration?: ScalePowerByDrawDuration;
}
