/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Weapon Item Component. Added to every weapon item such as axe, sword, trident, bow, crossbow.
 */
export interface Weapon {
  on_hit_block?: OnHitBlock;
  on_hurt_entity?: OnHurtEntity;
  on_not_hurt_entity?: OnNotHurtEntity;
}
/**
 * Trigger for letting you know when this item is used to hit a block.
 */
export interface OnHitBlock {}
/**
 * Trigger for letting you know when this item is used to hurt another mob.
 */
export interface OnHurtEntity {}
/**
 * Trigger for letting you know when this item hit another actor, but didn't do damage.
 */
export interface OnNotHurtEntity {}
