/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Sets if the item can be dropped by a dispenser block
 */
export type Dispensable = boolean;
/**
 * Which equipment slot the item can fit in
 */
export type Slot =
  | "slot.weapon.mainhand"
  | "none"
  | "slot.weapon.offhand"
  | "slot.armor.head"
  | "slot.armor.chest"
  | "slot.armor.legs"
  | "slot.armor.feet"
  | "slot.hotbar"
  | "slot.inventory"
  | "slot.enderchest"
  | "slot.saddle"
  | "slot.armor"
  | "slot.chest"
  | "slot.equippable";

/**
 * Wearable item component.
 */
export interface Wearable {
  dispensable?: Dispensable;
  slot?: Slot;
}
