/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The minecraft molang definition that results in a 3 floats.
 */
export type MolangArrayOf3Numbers =
  | []
  | [MolangNumber]
  | [MolangNumber, MolangNumber1]
  | [MolangNumber, MolangNumber1, MolangNumber2];
/**
 * The minecraft molang definition that results in a float.
 */
export type MolangNumber = string | number;
/**
 * The minecraft molang definition that results in a float.
 */
export type MolangNumber1 = string | number;
/**
 * The minecraft molang definition that results in a float.
 */
export type MolangNumber2 = string | number;
