/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * UNDOCUMENTED.
 */
export type BiomeName =
  | "animal"
  | "beach"
  | "birch"
  | "cold"
  | "dark_oak"
  | "deep"
  | "desert"
  | "edge"
  | "extreme_hills"
  | "flower_forest"
  | "forest"
  | "frozen"
  | "hills"
  | "ice"
  | "ice_plains"
  | "jungle"
  | "lakes"
  | "lukewarm"
  | "mega"
  | "mesa"
  | "monster"
  | "mooshroom_island"
  | "mountain"
  | "mutated"
  | "nether"
  | "ocean"
  | "plains"
  | "plateau"
  | "river"
  | "roofed"
  | "savanna"
  | "shore"
  | "stone"
  | "swamp"
  | "taiga"
  | "the_end"
  | "warm";
