/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The block id, for example: `minecraft:air'.
 */
export type Name = string;
/**
 * A single state of a block.
 */
export type State = string | boolean | number;

export interface Block {
  name?: Name;
  states?: States;
}
/**
 * The block states.
 */
export interface States {
  [k: string]: State;
}
