/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A language definitions file.
 */
export type Languages = (
  | "en_US"
  | "de_DE"
  | "ru_RU"
  | "zh_CN"
  | "fr_FR"
  | "it_IT"
  | "pt_BR"
  | "fr_CA"
  | "zh_TW"
  | "es_MX"
  | "es_ES"
  | "pt_PT"
  | "en_GB"
  | "ko_KR"
  | "ja_JP"
  | "nl_NL"
  | "bg_BG"
  | "cs_CZ"
  | "da_DK"
  | "el_GR"
  | "fi_FI"
  | "hu_HU"
  | "id_ID"
  | "nb_NO"
  | "pl_PL"
  | "sk_SK"
  | "sv_SE"
  | "tr_TR"
  | "uk_UA"
)[];
