/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The name of the pack as an identifier, they must be the same as the name of pack without spaces.
 */
export type SerializeName = string;
/**
 * The key in the language file to use to display text.
 */
export type LocatlizationName = string;
/**
 * The key in the language file to use to display text.
 */
export type LocatlizationName1 = string;
/**
 * The type of geometry to use.
 */
export type Geometry = string;
/**
 * The type of skin.
 */
export type Type = "free" | "paid";
/**
 * An array of item.
 */
export type Skins = Skin[];

/**
 * Skin pack definition.
 */
export interface SkipPack {
  serialize_name: SerializeName;
  localization_name: LocatlizationName;
  skins: Skins;
}
/**
 * A single skin definition.
 */
export interface Skin {
  localization_name: LocatlizationName1;
  geometry: Geometry;
  texture: Texture;
  type: Type;
}
/**
 * The filename of the skin.
 */
export interface Texture {
  [k: string]: unknown;
}
