/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This is the minimum difficulty level that a mob spawns.
 */
export type Min = "easy" | "normal" | "hard" | "peaceful";
/**
 * This is the maximum difficulty level that a mob spawns.
 */
export type Max = "easy" | "normal" | "hard" | "peaceful";

/**
 * This component allows players to set mobs spawn at certain difficulty levels. The min is for Peaceful difficulty and the max is for Hard difficulty.
 */
export interface DifficultyFilter {
  min?: Min;
  max?: Max;
}
