/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This component allows players to determine the herd size of animals.
 */
export type HeightFilter = Herd | Herd1[];
/**
 * UNDOCUMENTED.
 */
export type InitialEvent = string;
/**
 * UNDOCUMENTED.
 */
export type InitialEventCount = number;
/**
 * This is the minimum number of mobs that spawn in a herd.
 */
export type MinimumSize = number;
/**
 * This is the maximum number of mobs that spawn in a herd.
 */
export type MaximumSize = number;
/**
 * This is an event that can be triggered from spawning.
 */
export type Event = string;
/**
 * This is the number of mobs spawned before the specified event is triggered.
 */
export type EventSkipCount = number;

/**
 * Herd.
 */
export interface Herd {
  initial_event?: InitialEvent;
  initial_event_count?: InitialEventCount;
  min_size?: MinimumSize;
  max_size?: MaximumSize;
  event?: Event;
  event_skip_count?: EventSkipCount;
}
/**
 * Herd.
 */
export interface Herd1 {
  initial_event?: InitialEvent;
  initial_event_count?: InitialEventCount;
  min_size?: MinimumSize;
  max_size?: MaximumSize;
  event?: Event;
  event_skip_count?: EventSkipCount;
}
