/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The event String in this JSON Object is used to filter the spawn rules of the mob type. Can be type minecraft:pillager_patrols_event, minecraft:wandering_trader_event, or minecraft:ender_dragon_event..
 */
export type EventFilter =
  | "minecraft:pillager_patrols_event"
  | "minecraft:wandering_trader_event"
  | "minecraft:ender_dragon_event";

/**
 * This component allows players to spawn mobs on a particular event.
 */
export interface MobEventFilter {
  event?: EventFilter;
}
