/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This component allows an entity to spawn on a particular block. It includes a string or array of strings for the block they may spawn on.
 */
export type SpawnsOnBlockFilter = string | string[];
