/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * This is the minimum world_age_filter level that a mob spawns.
 */
export type Min = number;

/**
 * This component allows players to set mobs spawn after a certain amount of time has passed within a world.
 */
export interface WorldAgeFilter {
  min?: Min;
}
