/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * UNDOCUMENTED.
 */
export type RecipeIdentifier = string;
export type Tag = string;
/**
 * Recipe tags 1.12.0
 */
export type Tags = Tag[];
/**
 * Item used as base for the smithing recipe.
 */
export type Base = Item | Item[];
/**
 * Recipe item 1.12.0
 */
export type Item =
  | ItemIdentifier
  | {
      item: ItemIdentifier1;
      data?: ItemDataValue;
      count?: Count;
    };
export type ItemIdentifier = string;
export type ItemIdentifier1 = string;
export type ItemDataValue = number;
export type Count = number;
/**
 * Item used as addition for the smithing recipe.
 */
export type Addition = Item | Item[];
/**
 * When input items match the pattern then these items are the result.
 */
export type Result = Item | Item[];

/**
 * Represents a smithing table crafting recipe..
 */
export interface SmithingTransformRecipe1120 {
  description: Definition;
  tags?: Tags;
  base?: Base;
  addition?: Addition;
  result?: Result;
}
/**
 * Recipe definition 1.12.0
 */
export interface Definition {
  identifier?: RecipeIdentifier;
}
