/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * UNDOCUMENTED.
 */
export type RecipeIdentifier = string;
export type Tag = string;
/**
 * Recipe tags 1.12.0
 */
export type Tags = Tag[];
/**
 * Items used as input (without a shape) for the recipe.
 */
export type Ingredients = Item | Item[];
/**
 * Recipe item 1.12.0
 */
export type Item =
  | ItemIdentifier
  | {
      item: ItemIdentifier1;
      data?: ItemDataValue;
      count?: Count;
    };
export type ItemIdentifier = string;
export type ItemIdentifier1 = string;
export type ItemDataValue = number;
export type Count = number;
/**
 * UNDOCUMENTED.
 */
export type Group = string;
/**
 * Item used as output for the furnace recipe.
 */
export type Priority = number;
/**
 * When input items match the pattern then these items are the result.
 */
export type Result = Item | Item[];

/**
 * Represents a shapeless crafting recipe..
 */
export interface ShapelessRecipe1120 {
  description: Definition;
  tags?: Tags;
  ingredients?: Ingredients;
  group?: Group;
  priority?: Priority;
  result?: Result;
}
/**
 * Recipe definition 1.12.0
 */
export interface Definition {
  identifier?: RecipeIdentifier;
}
