/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * No features will be automatically attached to this Biome, only features specified in the minecraft:forced_features component will appear.
 */
export interface IgnoreAutomaticFeatures {}
