/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * UNDOCUMENTED.
 */
export type PeaksFactor = number;
/**
 * Block type use as steep material.
 */
export type Material = string;
/**
 * Enable for north facing slopes.
 */
export type NorthSlopes = boolean;
/**
 * Enable for south facing slopes.
 */
export type SouthSlopes = boolean;
/**
 * Enable for west facing slopes.
 */
export type WestSlopes = boolean;
/**
 * Enable for east facing slopes.
 */
export type EastSlopes = boolean;

/**
 * Noise parameters used to drive mountain terrain generation in Overworld.
 */
export interface MountainParameters {
  peaks_factor?: PeaksFactor;
  steep_material_adjustment?: SteepMaterialAdjustment;
  top_slide?: TopSlide;
}
/**
 * Defines surface material for steep slopes.
 */
export interface SteepMaterialAdjustment {
  material?: Material;
  north_slopes?: NorthSlopes;
  south_slopes?: SouthSlopes;
  west_slopes?: WestSlopes;
  east_slopes?: EastSlopes;
}
/**
 * Controls the density tapering that happens at the top of the world to prevent terrain from reaching too high.
 */
export interface TopSlide {
  enabled?: Enabled;
}
/**
 * If false, top slide will be disabled. If true, other parameters will be taken into account
 */
export interface Enabled {
  [k: string]: unknown;
}
