/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * UNDOCUMENTED.
 */
export type NoiseParams = [] | [number] | [number, number];
/**
 * UNDOCUMENTED.
 */
export type NoiseType =
  | "stone_beach"
  | "deep_ocean"
  | "default"
  | "default_mutated"
  | "lowlands"
  | "river"
  | "ocean"
  | "taiga"
  | "mountains"
  | "highlands"
  | "mushroom"
  | "less_extreme"
  | "extreme"
  | "beach"
  | "swamp";

/**
 * Noise parameters used to drive terrain height in the Overworld.
 */
export interface OverworldHeight {
  noise_params?: NoiseParams;
  noise_type?: NoiseType;
}
