/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Defines a range of noise values [min, max] for which this adjustment should be applied.
 */
export type HeightRange = [] | [Min] | [Min, Max];
/**
 * The minecraft molang definition that results in a float.
 */
export type Min = string | number;
/**
 * The minecraft molang definition that results in a float.
 */
export type Max = string | number;
/**
 * Controls the block type used for the surface of this biome when this adjustment is active.
 */
export type TopMaterial = string;
/**
 * Controls the block type used in a layer below the surface of this biome when this adjustment is active.
 */
export type MidMaterial = string;
/**
 * Controls the block type used as a floor for bodies of water in this biome when this adjustment is active.
 */
export type SeaFloorMaterial = string;
/**
 * Controls the block type used deep underground in this biome when this adjustment is active.
 */
export type TopMaterials = string;
/**
 * Controls the block type used in the bodies of water in this biome when this adjustment is active.
 */
export type TopMaterials1 = string;
/**
 * Defines a range of noise values [min, max] for which this adjustment should be applied.
 */
export type NoiseRange = [] | [Min1] | [Min1, Max1];
/**
 * All adjustments that match the column's noise values will be applied in the order listed.
 */
export type Adjustments = Adjustment[];

/**
 * Specify fine-detail changes to blocks used in terrain generation (based on a noise function).
 */
export interface SurfaceMaterialAdjustments {
  adjustments?: Adjustments;
}
/**
 * UNDOCUMENTED.
 */
export interface Adjustment {
  height_range?: HeightRange;
  materials?: Materials;
  noise_range?: NoiseRange;
}
/**
 * UNDOCUMENTED.
 */
export interface Materials {
  top_material?: TopMaterial;
  mid_material?: MidMaterial;
  sea_floor_material?: SeaFloorMaterial;
  foundation_material?: TopMaterials;
  sea_material?: TopMaterials1;
}
export interface Min1 {
  [k: string]: unknown;
}
export interface Max1 {
  [k: string]: unknown;
}
