/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * UNDOCUMENTED.
 */
export type Condition = string;
/**
 * UNDOCUMENTED.
 */
export type Chance = number;
/**
 * The maximum random chance value allowed.
 */
export type MaximumChance = number;

/**
 * Sets a random chance of the specified value.
 */
export interface RandomChance {
  condition?: Condition;
  chance?: Chance;
  max_chance?: MaximumChance;
}
