/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Describes the component that will trigger an even at a regular interval between two values.
 */
export type OnTick = string;
/**
 * Does the event loop.
 */
export type Looping = boolean;
/**
 * The Range between which the component will trigger his event.
 */
export type Range = unknown[];

/**
 * [Experimental] Describes the component that will trigger an even at a regular interval between two values.
 */
export interface RandomTicking {
  on_tick?: OnTick;
  looping?: Looping;
  range?: Range;
}
