/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * UNDOCUMENTED.
 */
export type Effect = string;
/**
 * UNDOCUMENTED.
 */
export type Target = "holder";
/**
 * UNDOCUMENTED.
 */
export type Duration = number;
/**
 * UNDOCUMENTED.
 */
export type Amplifier = number;
/**
 * UNDOCUMENTED.
 */
export type Type = "magic";
/**
 * UNDOCUMENTED.
 */
export type Amount = number;
/**
 * UNDOCUMENTED.
 */
export type Effect1 = string;
/**
 * UNDOCUMENTED.
 */
export type Target1 = "holder";
/**
 * UNDOCUMENTED.
 */
export type AngleOffset = number;
/**
 * UNDOCUMENTED.
 */
export type LaunchPower = number;
/**
 * UNDOCUMENTED.
 */
export type Projectile = string;
/**
 * UNDOCUMENTED.
 */
export type Target2 = "holder";
/**
 * UNDOCUMENTED.
 */
export type MaximumRange = [] | [X] | [X, Y] | [X, Y, Z];
/**
 * UNDOCUMENTED.
 */
export type X = number;
/**
 * UNDOCUMENTED.
 */
export type Y = number;
/**
 * UNDOCUMENTED.
 */
export type Z = number;
/**
 * UNDOCUMENTED.
 */
export type Transform = string;
/**
 * UNDOCUMENTED.
 */
export type Sequence = Sequence1[];
/**
 * UNDOCUMENTED.
 */
export type Weight = number;
/**
 * UNDOCUMENTED.
 */
export type Randomize = Randomize1[];
/**
 * UNDOCUMENTED.
 */
export type Command1 = string;
/**
 * UNDOCUMENTED.
 */
export type Command = Command1[];
/**
 * UNDOCUMENTED.
 */
export type Target3 = "other";

/**
 * UNDOCUMENTED.
 */
export interface Events {
  on_consume?: Event;
  [k: string]: Event;
}
/**
 * UNDOCUMENTED.
 */
export interface Event {
  sequence?: Sequence;
  randomize?: Randomize;
  run_command?: RunCommand;
}
/**
 * UNDOCUMENTED.
 */
export interface Sequence1 {
  add_mob_effect?: AddMobEffect;
  damage?: Shoot;
  decrement_stack?: DecrementStack;
  remove_mob_effect?: RemoveMobEffect;
  shoot?: Shoot1;
  swing?: Swing;
  teleport?: Teleport;
  transform_item?: TransformItem;
  [k: string]: unknown;
}
/**
 * UNDOCUMENTED.
 */
export interface AddMobEffect {
  effect?: Effect;
  target?: Target;
  duration?: Duration;
  amplifier?: Amplifier;
}
/**
 * UNDOCUMENTED.
 */
export interface Shoot {
  type?: Type;
  amount?: Amount;
}
/**
 * UNDOCUMENTED.
 */
export interface DecrementStack {}
/**
 * UNDOCUMENTED.
 */
export interface RemoveMobEffect {
  effect?: Effect1;
  target?: Target1;
}
/**
 * UNDOCUMENTED.
 */
export interface Shoot1 {
  angle_offset?: AngleOffset;
  launch_power?: LaunchPower;
  projectile?: Projectile;
}
/**
 * UNDOCUMENTED.
 */
export interface Swing {}
/**
 * UNDOCUMENTED.
 */
export interface Teleport {
  target?: Target2;
  max_range?: MaximumRange;
}
/**
 * UNDOCUMENTED.
 */
export interface TransformItem {
  transform?: Transform;
}
/**
 * UNDOCUMENTED.
 */
export interface Randomize1 {
  weight: Weight;
  [k: string]: unknown;
}
/**
 * UNDOCUMENTED.
 */
export interface RunCommand {
  command?: Command;
  target?: Target3;
}
