/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Rotation in xxx?
 */
export type Rotation = [] | [X] | [X, Y] | [X, Y, Z];
/**
 * Rotation in xxx?
 */
export type X = number;
/**
 * Rotation in xxx?
 */
export type Y = number;
/**
 * Rotation in xxx?
 */
export type Z = number;
/**
 * UNDOCUMENTED
 */
export type Scale = [] | [X1] | [X1, Y1] | [X1, Y1, Z1];
/**
 * UNDOCUMENTED
 */
export type X1 = number;
/**
 * UNDOCUMENTED
 */
export type Y1 = number;
/**
 * UNDOCUMENTED
 */
export type Z1 = number;
/**
 * UNDOCUMENTED
 */
export type Translation = [] | [X2] | [X2, Y2] | [X2, Y2, Z2];
/**
 * UNDOCUMENTED
 */
export type X2 = number;
/**
 * UNDOCUMENTED
 */
export type Y2 = number;
/**
 * UNDOCUMENTED
 */
export type Z2 = number;

/**
 * Supports rotation, scaling, and translation
 */
export interface Transformation {
  rotation?: Rotation;
  scale?: Scale;
  translation?: Translation;
}
