/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * UNDOCUMENTED.
 */
export type Function = "looting_enchant";

/**
 * The function looting_enchant.
 */
export interface LootingEnchant {
  function?: Function;
  count?: Count;
}
/**
 * UNDOCUMENTED.
 */
export interface Count {
  min?: number;
  max?: number;
}
