/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * UNDOCUMENTED.
 */
export type Function = "set_name";
/**
 * UNDOCUMENTED.
 */
export type Name = string;

/**
 * The function set_name.
 */
export interface SetName {
  function?: Function;
  name?: Name;
}
