/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * UNDOCUMENTED.
 */
export type Function = "set_data_from_color_index";

/**
 * The function set_data_from_color_index.
 */
export interface SetDataFromColorIndex {
  function?: Function;
}
