/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * UNDOCUMENTED.
 */
export type Function = "set_lore";
/**
 * UNDOCUMENTED.
 */
export type Lore = string[];

/**
 * The function set_lore.
 */
export interface SetLore {
  function?: Function;
  lore?: Lore;
}
