/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * UNDOCUMENTED.
 */
export type Function = "set_banner_details";
/**
 * UNDOCUMENTED.
 */
export type Type = number;

/**
 * The function set_banner_details.
 */
export interface SetBannerDetails {
  function?: Function;
  type?: Type;
}
