/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * UNDOCUMENTED.
 */
export type Function = "set_actor_id";
/**
 * UNDOCUMENTED.
 */
export type Id = string;

/**
 * The function set_actor_id.
 */
export interface SetActorId {
  function?: Function;
  id?: Id;
}
