/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * List of items that the entity drops when it grows up.
 */
export type DropItems = BlockceptionMinecraftItemDescriptor[] | BlockceptionMinecraftItemDescriptor1;
export type BlockceptionMinecraftItemDescriptor =
  | ItemIdentifier
  | ItemDescriptor
  | {
      item?: ItemIdentifier1 | ItemDescriptor1;
      [k: string]: unknown;
    };
/**
 * A minecraft item identifier.
 */
export type ItemIdentifier = string;
/**
 * [UNDOCUMENTED] A Molang expression ran against item or block to match.
 */
export type Molang = string;
/**
 * A minecraft item identifier.
 */
export type ItemIdentifier1 = string;
export type BlockceptionMinecraftItemDescriptor1 = (
  | ItemIdentifier
  | ItemDescriptor
  | {
      item?: ItemIdentifier1 | ItemDescriptor1;
      [k: string]: unknown;
    }
) &
  string;
/**
 * Amount of time before the entity grows up, -1 for always a baby.
 */
export type Duration = number;
/**
 * List of items that can be fed to the entity. Includes `item` for the item name and `growth` to define how much time it grows up by
 */
export type FeedItems =
  | (
      | ItemIdentifier
      | {
          growth?: number;
          item?: BlockceptionMinecraftItemDescriptor;
          [k: string]: unknown;
        }
    )[]
  | ItemIdentifier2;
/**
 * A minecraft item identifier.
 */
export type ItemIdentifier2 = string;
/**
 * The event to fire.
 */
export type Event = string;
/**
 * The target of the event.
 */
export type Target = "baby" | "block" | "damager" | "other" | "parent" | "player" | "self" | "target";
/**
 * The feed item used will transform to this item upon successful interaction. Format: itemName:auxValue
 */
export type TransformToItem =
  | ItemIdentifier
  | ItemDescriptor
  | {
      item?: ItemIdentifier1 | ItemDescriptor1;
      [k: string]: unknown;
    };

/**
 * Adds a timer for the entity to grow up. It can be accelerated by giving the entity the items it likes as defined by feedItems.
 */
export interface Ageable {
  drop_items?: DropItems;
  duration?: Duration;
  feed_items?: FeedItems;
  grow_up?: GrowUp;
  transform_to_item?: TransformToItem;
}
/**
 * An object that describes an item.
 */
export interface ItemDescriptor {
  tags?: Molang;
  /**
   * [UNDOCUMENTED] A tag to lookup item or block by.
   */
  item_tag?: string;
}
/**
 * An object that describes an item.
 */
export interface ItemDescriptor1 {
  tags?: Molang;
  /**
   * [UNDOCUMENTED] A tag to lookup item or block by.
   */
  item_tag?: string;
}
/**
 * Event to run when this entity grows up.
 */
export interface GrowUp {
  event?: Event;
  target?: Target;
}
