/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Allows the actor to open doors assuming that that flags set up for the component to use in navigation.
 */
export interface AnnotationOpenDoor {}
