/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The time in seconds required to break through doors.
 */
export type BreakTime = number;
/**
 * The minimum difficulty that the world must be on for this entity to break doors.
 */
export type MinimumDifficulty = string;

/**
 * Allows the actor to break doors assuming that that flags set up for the component to use in navigation.
 */
export interface AnnotationBreakDoor {
  break_time?: BreakTime;
  min_difficulty?: MinimumDifficulty;
}
