/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The Maximum distance from the boss at which the boss's health bar is present on the players screen.
 */
export type HudRange = number;
/**
 * The name that will be displayed above the boss's health bar.
 */
export type Name = string;
/**
 * Whether the sky should darken in the presence of the boss.
 */
export type ShouldDarkenSky = boolean;

/**
 * The current state of the boss for updating the boss HUD.
 */
export interface Boss {
  hud_range?: HudRange;
  name?: Name;
  should_darken_sky?: ShouldDarkenSky;
}
