/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * UNDOCUMENTED.
 */
export type BlockName = string;
/**
 * A list of the blocks that can be broken as this entity moves around.
 */
export type BreakableBlocks = BlockName[];

/**
 * Specifies the blocks that this entity can break as it moves around.
 */
export interface BreakBlocks {
  breakable_blocks?: BreakableBlocks;
}
