/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Specifies if/how a mob burns in daylight.
 */
export type BurnsInDaylight = BurnsInDaylight1 & BurnsInDaylight2;
export type BurnsInDaylight2 =
  | boolean
  | {
      [k: string]: unknown;
    };

export interface BurnsInDaylight1 {}
