/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Height of the collision box in blocks. A negative value will be assumed to be 0.
 */
export type Height = number;
/**
 * Width of the collision box in blocks. A negative value will be assumed to be 0.
 */
export type Width = number;

/**
 * Sets the width and height of the Entity's collision box.
 */
export interface CollisionBox {
  height?: Height;
  width?: Width;
}
