/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The second Palette Color value of the entity.
 */
export type Value = number;

/**
 * Defines the entity's second texture color. Only works on vanilla entities that have a second predefined color values (tropical fish).
 */
export interface Color0 {
  value?: Value;
}
