/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Determines if the mob will grant mobs of the same type combat buffs if they kill the target.
 */
export type ApplyToFamily = boolean;
/**
 * Determines if the mob will grant itself the combat buffs if it kills the target.
 */
export type ApplyToSelf = boolean;
/**
 * The duration in seconds of Regeneration I added to the mob.
 */
export type RegenerationDuration = number;

/**
 * Gives Regeneration I and removes Mining Fatigue from the mob that kills the Actor`s attack target.
 */
export interface CombatRegeneration {
  apply_to_family?: ApplyToFamily;
  apply_to_self?: ApplyToSelf;
  regeneration_duration?: RegenerationDuration;
}
