/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Amount of damage caused each hurt.
 */
export type DamagePerHurt = number;
/**
 * Time in seconds between damage.
 */
export type TimeBetweenHurt = number;

/**
 * Applies defined amount of damage to the entity at specified intervals.
 */
export interface DamageOverTime {
  damage_per_hurt?: DamagePerHurt;
  time_between_hurt?: TimeBetweenHurt;
}
