/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Angle in degrees.
 */
export type Value = number;

/**
 * Sets this entity's default head rotation angle.
 */
export interface DefaultLookAngle {
  value?: Value;
}
