/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Determines when the mob transforms, if the trades should be converted when the new mob has a economy_trade_table. When the trades are converted, the mob will generate a new trade list with their new trade table, but then it will try to convert any of the same trades over to have the same enchantments and user data. For example, if the original has a Emerald to Enchanted Iron Sword (Sharpness 1), and the new trade also has an Emerald for Enchanted Iron Sword, then the enchantment will be Sharpness 1.
 */
export type ConvertTradesEconomy = boolean;
/**
 * How much should the discount be modified by when the player has cured the Zombie Villager. Can be specified as a pair of numbers (low-tier trade discount and high-tier trade discount)
 */
export type CuredDiscount = [] | [A] | [A, B];
/**
 * Minimum.
 */
export type A = number;
/**
 * Maximum.
 */
export type B = number;
/**
 * Name to be displayed while trading with this entity.
 */
export type DisplayName = string;
/**
 * Used in legacy prices to determine how much should Demand be modified by when the player has the Hero of the Village mob effect.
 */
export type HeroDemandDiscount = number;
/**
 * The Maximum the discount can be modified by when the player has cured the Zombie Villager. Can be specified as a pair of numbers (low-tier trade discount and high-tier trade discount)
 */
export type MaximumCuredDiscount = [] | [A1] | [A1, B1];
/**
 * Minimum.
 */
export type A1 = number;
/**
 * Maximum.
 */
export type B1 = number;
/**
 * The Maximum the discount can be modified by when the player has cured a nearby Zombie Villager.
 */
export type MaximumNearbyCuredDiscount = number;
/**
 * How much should the discount be modified by when the player has cured a nearby Zombie Villager.
 */
export type NearbyCuredDiscount = number;
/**
 * Used to determine if trading with entity opens the new trade screen.
 */
export type NewScreen = boolean;
/**
 * Determines if the trades should persist when the mob transforms. This makes it so that the next time the mob is transformed to something with a trade_table or economy_trade_table, then it keeps their trades.
 */
export type PersistTrades = boolean;
/**
 * Show an in game trade screen when interacting with the mob.
 */
export type ShowTradeScreen = boolean;
/**
 * File path relative to the resource pack root for this entity's trades.
 */
export type Table = string;
/**
 * Determines whether the legacy formula is used to determines the trade prices.
 */
export type UseLegacyPriceFormula = boolean;

/**
 * Defines this entity's ability to trade with players.
 */
export interface EconomyTradeTable {
  convert_trades_economy?: ConvertTradesEconomy;
  cured_discount?: CuredDiscount;
  display_name?: DisplayName;
  hero_demand_discount?: HeroDemandDiscount;
  max_cured_discount?: MaximumCuredDiscount;
  max_nearby_cured_discount?: MaximumNearbyCuredDiscount;
  nearby_cured_discount?: NearbyCuredDiscount;
  new_screen?: NewScreen;
  persist_trades?: PersistTrades;
  show_trade_screen?: ShowTradeScreen;
  table?: Table;
  use_legacy_price_formula?: UseLegacyPriceFormula;
}
