/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Amount of exhaustion applied when attacking.
 */
export type Attack = number;
/**
 * Amount of exhaustion applied when taking damage.
 */
export type Damage = number;
/**
 * Amount of exhaustion applied when healed through food regeneration.
 */
export type Heal = number;
/**
 * Amount of exhaustion applied when jumping.
 */
export type Jump = number;
/**
 * Amount of exhaustion applied when mining.
 */
export type Mine = number;
/**
 * Amount of exhaustion applied when sprinting.
 */
export type Sprint = number;
/**
 * Amount of exhaustion applied when sprint jumping.
 */
export type SprintJump = number;
/**
 * Amount of exhaustion applied when swimming.
 */
export type Swim = number;
/**
 * Amount of exhaustion applied when walking.
 */
export type Walk = number;

/**
 * Defines how much exhaustion each player action should take.
 */
export interface ExhaustionValues {
  attack?: Attack;
  damage?: Damage;
  heal?: Heal;
  jump?: Jump;
  mine?: Mine;
  sprint?: Sprint;
  sprint_jump?: SprintJump;
  swim?: Swim;
  walk?: Walk;
}
