/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A molang expression defining the amount of experience rewarded when this entity is successfully bred. An array of expressions adds each expression's result together for a final total.
 */
export type OnBred = string | number;
/**
 * A molang expression defining the amount of experience rewarded when this entity dies. An array of expressions adds each expression's result together for a final total.
 */
export type OnDeath = string | number;

/**
 * Defines the amount of experience rewarded when the entity dies or is successfully bred.
 */
export interface ExperienceReward {
  on_bred?: OnBred;
  on_death?: OnDeath;
}
