/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The value of the entity's offset from the terrain, in blocks.
 */
export type Value = number;

/**
 * Sets the offset from the ground that the entity is actually at.
 */
export interface GroundOffset {
  value?: Value;
}
