/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Value between 0-1. Chance of success per tick.
 */
export type Chance = number;
/**
 * Number of charges.
 */
export type Charges = number;

/**
 * Could increase crop growth when entity walks over crop.
 */
export interface GrowsCrop {
  chance?: Chance;
  charges?: Charges;
}
