/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A Molang expression defining the inter-beat interval in seconds. A value of zero or less means no heartbeat..
 */
export type Interval = string | number;
/**
 * Level sound event to be played as the heartbeat sound.
 */
export type SoundEvent = string;

/**
 * defines the entity's heartbeat..
 */
export interface Heartbeat {
  interval?: Interval;
  sound_event?: SoundEvent;
}
