/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The radius that the entity will be restricted to in relation to its home.
 */
export type RestrictionRadius = number;
/**
 * Optional block that the home position will be associated with. If any of the blocks no longer exist at that position, the home restriction is removed. Example syntax: minecraft:sand. Not supported: minecraft:sand:1
 */
export type HomeBlock = string;
/**
 * Optional block list that the home position will be associated with. If any of the blocks no longer exist at that position, the home restriction is removed. Example syntax: minecraft:sand. Not supported: minecraft:sand:1
 */
export type HomeBlockList = HomeBlock[];

/**
 * Saves a home pos for when the the entity is spawned.
 */
export interface Home {
  restriction_radius?: RestrictionRadius;
  home_block_list?: HomeBlockList;
}
