/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * If true, all entities linked to this entity in a child relationship (eg. leashed) will also be despawned.
 */
export type RemoveChildEntities = boolean;

/**
 * Despawns the Actor immediately.
 */
export interface InstantDespawn {
  remove_child_entities?: RemoveChildEntities;
}
