/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Number of slots that this entity can gain per extra strength.
 */
export type AdditionalSlotsPerStrength = number;
/**
 * If true, the contents of this inventory can be removed by a hopper.
 */
export type CanBeSiphonedFrom = boolean;
/**
 * Type of container this entity has. Can be horse, minecart_chest, chest_boat, minecart_hopper, inventory, container or hopper
 */
export type ContainerType =
  | "horse"
  | "minecart_chest"
  | "chest_boat"
  | "minecart_hopper"
  | "inventory"
  | "container"
  | "hopper";
/**
 * Number of slots the container has.
 */
export type InventorySize = number;
/**
 * If true, only the entity can access the inventory.
 */
export type Private = boolean;
/**
 * If true, the entity's inventory can only be accessed by its owner or itself.
 */
export type RestrictToOwner = boolean;

/**
 * Defines this entity's inventory properties.
 */
export interface Inventory {
  additional_slots_per_strength?: AdditionalSlotsPerStrength;
  can_be_siphoned_from?: CanBeSiphonedFrom;
  container_type?: ContainerType;
  inventory_size?: InventorySize;
  private?: Private;
  restrict_to_owner?: RestrictToOwner;
}
