/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The text that will display when interacting with this entity with a dye when playing with Touch-screen controls.
 */
export type InteractText = string;

/**
 * Allows dyes to be used on this entity to change its color.
 */
export interface IsDyeable {
  interact_text?: InteractText;
}
