/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The path to the loot table, relative to the Behavior Pack's root.
 */
export type Table = string;

/**
 * sets the loot table for what items this entity drops upon death.
 */
export interface Loot {
  table: Table;
}
