/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The ID of the variant. By convention, 0 is the ID of the base entity
 */
export type Value = number;

/**
 * Additional variant value. Can be used to further differentiate variants.
 */
export interface MarkVariant {
  value: Value;
}
