/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The higher the number, the less often the movement sound will be played.
 */
export type Value = number;

/**
 * Sets the offset used to determine the next step distance for playing a movement sound.
 */
export interface MovementSoundDistanceOffset {
  value: Value;
}
