/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The maximum number in degrees the mob can turn per tick.
 */
export type MaximumTurn = number;
/**
 * Strength of the sway movement.
 */
export type SwayAmplitude = number;
/**
 * Multiplier for the frequency of the sway movement.
 */
export type SwayAmplitude1 = number;

/**
 * This move control causes the mob to sway side to side giving the impression it is swimming.
 */
export interface MovementSway {
  max_turn?: MaximumTurn;
  sway_amplitude?: SwayAmplitude;
  sway_frequency?: SwayAmplitude1;
}
