/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The initial value of the player exhaustion.
 */
export type Value = number;
/**
 * The maximum player exhaustion of this entity.
 */
export type Maximum = number;

/**
 * Defines the player's exhaustion level.
 */
export interface PlayerExhaustion {
  value?: Value;
  max?: Maximum;
}
