/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Whether the entity can be pushed by other entities.
 */
export type IsPushable = boolean;
/**
 * Whether the entity can be pushed by pistons safely.
 */
export type IsPushableByPiston = boolean;

/**
 * Defines what can push an entity between other entities and pistons.
 */
export interface Pushable {
  is_pushable?: IsPushable;
  is_pushable_by_piston?: IsPushableByPiston;
}
