/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The strength with which blocking entities should be knocked back.
 */
export type KnockbackStrength = number;
/**
 * The chance of this reaction being picked.
 */
export type Weight = number;
/**
 * An event that runs when this reaction is picked.
 */
export type Value =
  | string
  | {
      event?: Event;
      target?: Target;
      [k: string]: unknown;
    };
/**
 * The event to fire.
 */
export type Event = string;
/**
 * The target of the event.
 */
export type Target = "baby" | "block" | "damager" | "other" | "parent" | "player" | "self" | "target";
/**
 * A list of weighted responses to the melee attack being blocked.
 */
export type ReactionChoices = {
  weight?: Weight;
  value?: Value;
}[];

/**
 * Defines the ravager's response to their melee attack being blocked.
 */
export interface RavagerBlocked {
  knockback_strength?: KnockbackStrength;
  reaction_choices?: ReactionChoices;
}
