/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Ending scale of the entity when it's fully grown.
 */
export type EndScale = number;
/**
 * Initial scale of the newborn entity.
 */
export type StartScale = number;

/**
 * Defines the entity's size interpolation based on the entity's age.
 */
export interface ScaleByAge {
  end_scale?: EndScale;
  start_scale?: StartScale;
}
