/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * ID of the Potion effect to be applied on hit.
 */
export type AuxVal = number;
/**
 * Actor definition to use as projectile for the ranged attack. The actor definition must have the projectile component to be able to be shot as a projectile
 */
export type Def = string;
/**
 * Sets whether the projectiles being used are flagged as magic. If set, the ranged attack goal will not be used at the same time as other magic goals, such as minecraft:behavior.drink_potion.
 */
export type Magic = boolean;
/**
 * Velocity in which the projectiles will be shot. A power of 0 will be overwritten by the default projectile throw power.
 */
export type Power = number;
/**
 * Projectiles that can be used by the shooter
 */
export type Projectile = string;
/**
 * List of projectiles that can be used by the shooter. Projectiles are evaluated in the order of the list; after a projectile is chosen, the rest of the list is ignored.
 */
export type Projectiles = Projectile[];
/**
 * Sound that is played when the shooter shoots a projectile.
 */
export type Sound = string;

/**
 * Defines the entity's ranged attack behavior.
 */
export interface Shooter {
  aux_val?: AuxVal;
  def?: Def;
  magic?: Magic;
  power?: Power;
  projectiles?: Projectiles;
  sound?: Sound;
}
