/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The value of the volume the entity uses for sound effects.
 */
export type Value = number;

/**
 * Sets the entity's base volume for sound effects.
 */
export interface SoundVolume {
  value?: Value;
}
