/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The distance at which the closest player has to be before this entity despawns. This option will be ignored if never_despawn is true. Min: 128 blocks.
 */
export type DistanceToPlayers = number;
/**
 * If true, this entity will not despawn even if players are far away. If false, distance_to_players will be used to determine when to despawn.
 */
export type NeverDespawn = boolean;
/**
 * The area around the entity to tick. Default: 2. Allowed range: 2-6.
 */
export type Radius = number;

/**
 * Defines if the entity ticks the world and the radius around it to tick.
 */
export interface TickWorld {
  distance_to_players?: DistanceToPlayers;
  never_despawn?: NeverDespawn;
  radius?: Radius;
}
