/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The chance of the entity trusting with each item use between 0.0 and 1.0, where 1.0 is 100%
 */
export type Probability = number;
/**
 * The event to fire.
 */
export type Event = string;
/**
 * The target of the event.
 */
export type Target = "baby" | "block" | "damager" | "other" | "parent" | "player" | "self" | "target";
/**
 * A minecraft item identifier.
 */
export type TrustItem = string;
/**
 * The list of items that can be used to get the entity to trust players.
 */
export type TrustItems = TrustItem[];

/**
 * Defines the rules for a mob to trust players.
 */
export interface Trusting {
  probability?: Probability;
  trust_event?: TrustEvent;
  trust_items?: TrustItems;
}
/**
 * Event to run when this entity becomes trusting.
 */
export interface TrustEvent {
  event?: Event;
  target?: Target;
}
