/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Family name.
 */
export type Family1 = string;
/**
 * List of family names.
 */
export type Family = Family1[];

/**
 * Defines the families this entity belongs to.
 */
export interface TypeFamily {
  family: Family;
}
