/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The maximum auto step height when on any other block.
 */
export type BaseValue = number;
/**
 * The maximum auto step height when on a block that prevents jumping.
 */
export type JumpPreventedValue = number;

/**
 * Entities with this component will have a maximum auto step height that is different depending on wether they are on a block that prevents jumping. Incompatible with "runtime_identifier": "minecraft:horse".
 */
export interface VariableMaxAutoStep {
  base_value?: BaseValue;
  jump_prevented_value?: JumpPreventedValue;
}
