/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The higher the number, the faster the animation for walking plays. A value of 1.0 means normal speed, while 2.0 means twice as fast
 */
export type Value = number;

/**
 * Sets the speed multiplier for this entity's walk animation speed.
 */
export interface WalkAnimationSpeed {
  value?: Value;
}
