/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Drag factor to determine movement speed when in water.
 */
export type DragFactor = number;

/**
 * Defines the speed with which an entity can move through water.
 */
export interface WaterMovement {
  drag_factor?: DragFactor;
}
