/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type SliceOffsets = number | [number, number, number, number];
/**
 * Width and height of the texture (in this exact order).
 *
 * @minItems 2
 * @maxItems 2
 */
export type SizeOfTheTexture = [number, number];

/**
 * The file that specifies 9Slice textures.
 */
export interface SliceTextureFile {
  nineslice_size?: SliceOffsets;
  base_size?: SizeOfTheTexture;
}
