/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Returns true when the float actor property matches the value provided.
 */
export type TestProperty = string;
/**
 * (Required) The property name to look for
 */
export type Operator = string;
/**
 * (Optional) The comparison to apply with `value`.
 */
export type Operator1 = "!=" | "<" | "<=" | "<>" | "=" | "==" | ">" | ">=" | "equals" | "not";
/**
 * (Optional) The subject of this filter test.
 */
export type Subject = "block" | "other" | "parent" | "player" | "self" | "target" | "damager";
/**
 * (Required) A floating point value.
 */
export type Value = number;

/**
 * Returns true when the float actor property matches the value provided.
 */
export interface FloatProperty {
  test?: TestProperty;
  domain: Operator;
  operator?: Operator1;
  subject?: Subject;
  value: Value;
  [k: string]: unknown;
}
