/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * How important this behavior is. Lower priority behaviors will be executed first.
 */
export type Priority = number;

/**
 * Enables the mob to barter for items that have been configured as barter currency. Must be used in combination with the barter component
 */
export interface Barter {
  priority?: Priority;
}
