/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * How important this behavior is. Lower priority behaviors will be executed first.
 */
export type Priority = number;
/**
 * Movement speed multiplier of the mob when using this AI Goal.
 */
export type SpeedMultiplier = number;
/**
 * Minimum and maximum time between firework (positive, in seconds).
 */
export type FireworksInterval =
  | number
  | []
  | [A]
  | [A, B]
  | {
      range_min?: RangeMin;
      range_max?: RangeMax;
    };
/**
 * The first value of the range.
 */
export type A = number;
/**
 * The second value of the range.
 */
export type B = number;
/**
 * The minimum value of the range.
 */
export type RangeMin = number;
/**
 * The maximum value of the range.
 */
export type RangeMax = number;
/**
 * The duration in seconds that the celebration lasts for.
 */
export type Duration = number;
/**
 * The event to trigger when the goal's duration expires.
 */
export type OnCelebrationEndEvent =
  | string
  | {
      event?: Event;
      target?: Target;
      [k: string]: unknown;
    };
/**
 * The event to fire.
 */
export type Event = string;
/**
 * The target of the event.
 */
export type Target = "baby" | "block" | "damager" | "other" | "parent" | "player" | "self" | "target";

/**
 * Allows this entity to celebrate surviving a raid by shooting fireworks.
 */
export interface CelebrateSurvive {
  priority?: Priority;
  speed_multiplier?: SpeedMultiplier;
  fireworks_interval?: FireworksInterval;
  duration?: Duration;
  on_celebration_end_event?: OnCelebrationEndEvent;
}
