/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * How important this behavior is. Lower priority behaviors will be executed first.
 */
export type Priority = number;
/**
 * If true, this behavior can run when this entity is named. Otherwise not.
 */
export type AllowDigWhenNamed = boolean;
/**
 * Indicates that the actor should start digging when it sees daylight.
 */
export type DigsInDaylight = boolean;
/**
 * Goal duration in seconds.
 */
export type Duration = number;
/**
 * The minimum idle time in seconds between the last detected disturbance to the start of digging.
 */
export type IdleTime = number;
/**
 * If true, finding new suspicious locations count as disturbances that may delay the start of this goal.
 */
export type SuspicionIsDisturbance = boolean;
/**
 * If true, vibrations count as disturbances that may delay the start of this goal.
 */
export type VibrationIsDisturbance = boolean;

/**
 * [EXPERIMENTAL BEHAVIOR] Activates the `DIGGING` actor flag during the specified duration. Currently only Warden can use the Dig goal
 */
export interface Dig {
  priority?: Priority;
  allow_dig_when_named?: AllowDigWhenNamed;
  digs_in_daylight?: DigsInDaylight;
  duration?: Duration;
  idle_time?: IdleTime;
  suspicion_is_disturbance?: SuspicionIsDisturbance;
  vibration_is_disturbance?: VibrationIsDisturbance;
}
