/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * How important this behavior is. Lower priority behaviors will be executed first.
 */
export type Priority = number;
/**
 * The speed this entity moves when this behavior has started or while it's active.
 */
export type ActiveSpeed = number;
/**
 * Maximum distance of this entity's fireball attack while strafing.
 */
export type FireballRange = number;
/**
 * The speed this entity moves while this behavior is not active.
 */
export type FlightSpeed = number;
/**
 * Percent chance to to switch this entity's strafe direction between clockwise and counterclockwise. Switch direction chance occurs each time a new target is chosen (1.0 = 100%).
 */
export type SwitchDirectionProbability = number;
/**
 * Time (in seconds) the target must be in fireball range, and in view [ie, no solid terrain in-between the target and this entity], before a fireball can be shot.
 */
export type TargetInRangeAndInViewTime = number;
/**
 * Minimum and maximum distance, from the target, this entity can use this behavior.
 */
export type TargetZone =
  | number
  | []
  | [A]
  | [A, B]
  | {
      range_min?: RangeMin;
      range_max?: RangeMax;
    };
/**
 * The first value of the range.
 */
export type A = number;
/**
 * The second value of the range.
 */
export type B = number;
/**
 * The minimum value of the range.
 */
export type RangeMin = number;
/**
 * The maximum value of the range.
 */
export type RangeMax = number;
/**
 * The speed at which this entity turns while using this behavior.
 */
export type TurnSpeed = number;
/**
 * The target must be within "view_angle" degrees of the dragon's current rotation before a fireball can be shot.
 */
export type ViewAngle = number;

/**
 * Allows this entity to fly around looking for a player to shoot fireballs at. Note: This behavior can only be used by the ender_dragon entity type.
 */
export interface Dragonstrafeplayer {
  priority?: Priority;
  active_speed?: ActiveSpeed;
  fireball_range?: FireballRange;
  flight_speed?: FlightSpeed;
  switch_direction_probability?: SwitchDirectionProbability;
  target_in_range_and_in_view_time?: TargetInRangeAndInViewTime;
  target_zone?: TargetZone;
  turn_speed?: TurnSpeed;
  view_angle?: ViewAngle;
}
