/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * How important this behavior is. Lower priority behaviors will be executed first.
 */
export type Priority = number;
/**
 * Movement speed multiplier of the mob when using this AI Goal.
 */
export type SpeedMultiplier = number;
/**
 * The distance from the boundary the villager must be within in to explore the outskirts.
 */
export type DistFromBoundary = [] | [X] | [X, Y] | [X, Y, Z];
/**
 * The X component.
 */
export type X = number;
/**
 * The Y component.
 */
export type Y = number;
/**
 * The Z component.
 */
export type Z = number;
/**
 * Total distance in blocks the the entity will explore beyond the village bounds when choosing its travel point.
 */
export type ExploreDist = number;
/**
 * This is the maximum amount of time an entity will attempt to reach it's travel point on the outskirts of the village before the goal exits.
 */
export type MaxTravelTime = number;
/**
 * The wait time in seconds between choosing new explore points will be chosen on a random interval between this value and the minimum wait time. This value is also the total amount of time the entity will explore random points before the goal stops.
 */
export type MaxWaitTime = number;
/**
 * The entity must be within this distance for it to consider it has successfully reached its target.
 */
export type MinDistFromTarget = number;
/**
 * The minimum perimeter of the village required to run this goal.
 */
export type MinPerimeter = number;
/**
 * The wait time in seconds between choosing new explore points will be chosen on a random interval between this value and the maximum wait time.
 */
export type MinWaitTime = number;
/**
 * A new explore point will randomly be chosen within this XZ distance of the current target position when navigation has finished and the wait timer has elapsed.
 */
export type NextXZ = number;
/**
 * A new explore point will randomly be chosen within this Y distance of the current target position when navigation has finished and the wait timer has elapsed.
 */
export type NextY = number;
/**
 * Each new explore point will be chosen on a random interval between the minimum and the maximum wait time, divided by this value. This does not apply to the first explore point chosen when the goal runs.
 */
export type TimerRatio = number;

/**
 * Allows the entity to first travel to a random point on the outskirts of the village, and then explore random points within a small distance. This goal requires "minecraft:dweller" and "minecraft:navigation" to execute.
 */
export interface ExploreOutskirts {
  priority?: Priority;
  speed_multiplier?: SpeedMultiplier;
  dist_from_boundary?: DistFromBoundary;
  explore_dist?: ExploreDist;
  max_travel_time?: MaxTravelTime;
  max_wait_time?: MaxWaitTime;
  min_dist_from_target?: MinDistFromTarget;
  min_perimeter?: MinPerimeter;
  min_wait_time?: MinWaitTime;
  next_xz?: NextXZ;
  next_y?: NextY;
  timer_ratio?: TimerRatio;
}
