/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * How important this behavior is. Lower priority behaviors will be executed first.
 */
export type Priority = number;
/**
 * Movement speed multiplier of the mob when using this AI Goal.
 */
export type SpeedMultiplier = number;
/**
 * Time in seconds the mob has to wait before using the goal again.
 */
export type CooldownTime = number;

/**
 * Allows the mob to seek shade.
 */
export interface FindCover {
  priority?: Priority;
  speed_multiplier?: SpeedMultiplier;
  cooldown_time?: CooldownTime;
}
