/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * How important this behavior is. Lower priority behaviors will be executed first.
 */
export type Priority = number;
/**
 * Distance in blocks on ground that the mob will look for a new spot to move to. Must be at least 1
 */
export type XzDist = number;
/**
 * Distance in blocks that the mob will look up or down for a new spot to move to. Must be at least 1
 */
export type YDist = number;
/**
 * Height in blocks to add to the selected target position.
 */
export type YOffset = number;
/**
 * If true, the point has to be reachable to be a valid target.
 */
export type MustReach = boolean;
/**
 * If true, the mob will randomly pick a new point while moving to the previously selected one.
 */
export type RandomReselect = boolean;
/**
 * Range of time in seconds the mob will float around before landing and choosing to do something else.
 */
export type FloatDuration =
  | number
  | []
  | [A]
  | [A, B]
  | {
      range_min?: RangeMin;
      range_max?: RangeMax;
    };
/**
 * The first value of the range.
 */
export type A = number;
/**
 * The second value of the range.
 */
export type B = number;
/**
 * The minimum value of the range.
 */
export type RangeMin = number;
/**
 * The maximum value of the range.
 */
export type RangeMax = number;

/**
 * Allows the mob to float around like the Ghast.
 */
export interface FloatWander {
  priority?: Priority;
  xz_dist?: XzDist;
  y_dist?: YDist;
  y_offset?: YOffset;
  must_reach?: MustReach;
  random_reselect?: RandomReselect;
  float_duration?: FloatDuration;
}
