/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * How important this behavior is. Lower priority behaviors will be executed first.
 */
export type Priority = number;
/**
 * Movement speed multiplier of the mob when using this AI Goal.
 */
export type SpeedMultiplier = number;
/**
 * Amount of time in seconds that the mob reacts.
 */
export type Duration = number;
/**
 * Defines what POI type to hide at.
 */
export type PointOfInterestType = string;
/**
 * The cooldown time in seconds before the goal can be reused after a internal failure or timeout condition.
 */
export type TimeoutCooldown = number;

/**
 * Allows a mob with the hide component to attempt to move to - and hide at - an owned or nearby POI.
 */
export interface Hide {
  priority?: Priority;
  speed_multiplier?: SpeedMultiplier;
  duration?: Duration;
  poi_type?: PointOfInterestType;
  timeout_cooldown?: TimeoutCooldown;
}
