/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * How important this behavior is. Lower priority behaviors will be executed first.
 */
export type Priority = number;
/**
 * Whether to broadcast out the mob's target to other mobs of the same type.
 */
export type Broadcast = boolean;
/**
 * Range in blocks for how far to broadcast.
 */
export type BroadcastRange = number;
/**
 * Minimum distance the target must be for the mob to run this goal.
 */
export type MinimumRadius = number;
/**
 * Event to run when target is within the radius. This event is broadcasted if broadcast is true.
 */
export type WithinRadiusEvent =
  | string
  | {
      event?: Event;
      target?: Target;
      [k: string]: unknown;
    };
/**
 * The event to fire.
 */
export type Event = string;
/**
 * The target of the event.
 */
export type Target = "baby" | "block" | "damager" | "other" | "parent" | "player" | "self" | "target";

/**
 * The mob freezes and looks at the mob they are targeting.
 */
export interface HoldGround {
  priority?: Priority;
  broadcast?: Broadcast;
  broadcast_range?: BroadcastRange;
  min_radius?: MinimumRadius;
  within_radius_event?: WithinRadiusEvent;
}
