/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * How important this behavior is. Lower priority behaviors will be executed first.
 */
export type Priority = number;
/**
 * If true, the mob will only jump at its target if its on the ground. Setting it to false will allow it to jump even if its already in the air
 */
export type MustBeOnGround = boolean;
/**
 * Allows the actor to be set to persist upon targeting a player.
 */
export type SetPersistent = boolean;
/**
 * The height in blocks the mob jumps when leaping at its target.
 */
export type Yd = number;
/**
 * Distance in blocks the mob jumps when leaping at its target.
 */
export type TargetDist = number;

/**
 * Allows monsters to jump at and attack their target. Can only be used by hostile mobs.
 */
export interface LeapAtTarget {
  priority?: Priority;
  must_be_on_ground?: MustBeOnGround;
  set_persistent?: SetPersistent;
  yd?: Yd;
  target_dist?: TargetDist;
}
