/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * How important this behavior is. Lower priority behaviors will be executed first.
 */
export type Priority = number;
/**
 * The distance in blocks from which the entity will look at.
 */
export type LookDistance = number;
/**
 * The probability of looking at the target. A value of 1.00 is 100%
 */
export type Probability = number;
/**
 * Time range to look at the entity.
 */
export type LookTime =
  | number
  | []
  | [A]
  | [A, B]
  | {
      range_min?: RangeMin;
      range_max?: RangeMax;
    };
/**
 * The first value of the range.
 */
export type A = number;
/**
 * The second value of the range.
 */
export type B = number;
/**
 * The minimum value of the range.
 */
export type RangeMin = number;
/**
 * The maximum value of the range.
 */
export type RangeMax = number;
/**
 * The angle in degrees that the mob can see in the X-axis (left-right).
 */
export type AngleOfViewVertical = number;
/**
 * The angle in degrees that the mob can see in the Y-axis (up-down).
 */
export type AngleOfViewHorizontal = number;

/**
 * Allows the mob to look at the player they are trading with.
 */
export interface LookAtTradingPlayer {
  priority?: Priority;
  look_distance?: LookDistance;
  probability?: Probability;
  look_time?: LookTime;
  angle_of_view_vertical?: AngleOfViewVertical;
  angle_of_view_horizontal?: AngleOfViewHorizontal;
}
