/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * How important this behavior is. Lower priority behaviors will be executed first.
 */
export type Priority = number;
/**
 * Movement speed multiplier of the mob when using this AI Goal.
 */
export type SpeedMultiplier = number;
/**
 * The distance at which this mob wants to be away from its target.
 */
export type TargetDist = number;
/**
 * If true, this mob will chase after the target as long as it's a valid target.
 */
export type TrackTarget = boolean;

/**
 * Allows the mob to move around on its own while mounted seeking a target to attack.
 */
export interface MountPathing {
  priority?: Priority;
  speed_multiplier?: SpeedMultiplier;
  target_dist?: TargetDist;
  track_target?: TrackTarget;
}
