/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * How important this behavior is. Lower priority behaviors will be executed first.
 */
export type Priority = number;
/**
 * Movement speed multiplier of the mob when using this AI Goal.
 */
export type SpeedMultiplier = number;
/**
 * If true, the mob will only move through the village during night time.
 */
export type OnlyAtNight = boolean;

/**
 * Can only be used by Villagers. Allows the villagers to create paths around the village.
 */
export interface MoveThroughVillage {
  priority?: Priority;
  speed_multiplier?: SpeedMultiplier;
  only_at_night?: OnlyAtNight;
}
