/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * How important this behavior is. Lower priority behaviors will be executed first.
 */
export type Priority = number;
/**
 * Movement speed multiplier of the mob when using this AI Goal.
 */
export type SpeedMultiplier = number;

/**
 * Allows mobs with the dweller component to move toward their Village area that the mob should be restricted to.
 */
export interface MoveTowardsDwellingRestriction {
  priority?: Priority;
  speed_multiplier?: SpeedMultiplier;
}
