/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * How important this behavior is. Lower priority behaviors will be executed first.
 */
export type Priority = number;
/**
 * Movement speed multiplier of the mob when using this AI Goal.
 */
export type SpeedMultiplier = number;
/**
 * Percent chance that the mob will start this goal, from 0 to 1.
 */
export type ChanceToStart = number;
/**
 * The distance (in blocks) that the mob tries to be in range of the friend it's following.
 */
export type FollowDistance = number;
/**
 * The dimensions of the AABB used to search for a potential friend to play with.
 */
export type FriendSearchArea = [] | [X] | [X, Y] | [X, Y, Z];
/**
 * The X component.
 */
export type X = number;
/**
 * The Y component.
 */
export type Y = number;
/**
 * The Z component.
 */
export type Z = number;
/**
 * The entity type(s) to consider when searching for a potential friend to play with.
 */
export type FriendTypes = {
  [k: string]: unknown;
}[];
/**
 * The max amount of seconds that the mob will play for before exiting the Goal.
 */
export type MaxPlayDurationSeconds = number;
/**
 * The height (in blocks) that the mob will search within to find a random position position to move to. Must be at least 1.
 */
export type RandomPosSearchHeight = number;
/**
 * The distance (in blocks) on ground that the mob will search within to find a random position to move to. Must be at least 1.
 */
export type RandomPosSearchRange = number;

/**
 * Allows the mob to play with other baby villagers. This can only be used by Villagers.
 */
export interface Play {
  priority?: Priority;
  speed_multiplier?: SpeedMultiplier;
  chance_to_start?: ChanceToStart;
  follow_distance?: FollowDistance;
  friend_search_area?: FriendSearchArea;
  friend_types?: FriendTypes;
  max_play_duration_seconds?: MaxPlayDurationSeconds;
  random_pos_search_height?: RandomPosSearchHeight;
  random_pos_search_range?: RandomPosSearchRange;
}
