/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * How important this behavior is. Lower priority behaviors will be executed first.
 */
export type Priority = number;
/**
 * Movement speed multiplier of the mob when using this AI Goal.
 */
export type SpeedMultiplier = number;
/**
 * If true, the mob will avoid blocks that cause damage.
 */
export type AvoidDamageBlocks = boolean;
/**
 * If true, the mob can stop flying and land on a tree instead of the ground.
 */
export type CanLandOnTrees = boolean;
/**
 * Distance in blocks on ground that the mob will look for a new spot to move to. Must be at least 1
 */
export type XzDist = number;
/**
 * Distance in blocks that the mob will look up or down for a new spot to move to. Must be at least 1
 */
export type YDist = number;
/**
 * Height in blocks to add to the selected target position.
 */
export type YOffset = number;

/**
 * Allows a mob to randomly fly around.
 */
export interface RandomFly {
  priority?: Priority;
  speed_multiplier?: SpeedMultiplier;
  avoid_damage_blocks?: AvoidDamageBlocks;
  can_land_on_trees?: CanLandOnTrees;
  xz_dist?: XzDist;
  y_dist?: YDist;
  y_offset?: YOffset;
}
