/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * How important this behavior is. Lower priority behaviors will be executed first.
 */
export type Priority = number;
/**
 * Movement speed multiplier of the mob when using this AI Goal.
 */
export type SpeedMultiplier = number;
/**
 * Time in seconds the mob has to wait before using the goal again.
 */
export type Cooldown = number;
/**
 * Time in seconds the mob has to wait before using the goal again.
 */
export type CooldownTime = number;
/**
 * The minimum amount of time in seconds before the mob can stand back up.
 */
export type MinimumSitTime = number;
/**
 * This is the chance that the mob will start this goal, from 0 to 1.
 */
export type StartChance = number;
/**
 * This is the chance that the mob will stop this goal, from 0 to 1.
 */
export type StopChance = number;

/**
 * Allows the mob to randomly sit for a duration.
 */
export interface RandomSitting {
  priority?: Priority;
  speed_multiplier?: SpeedMultiplier;
  cooldown?: Cooldown;
  cooldown_time?: CooldownTime;
  min_sit_time?: MinimumSitTime;
  start_chance?: StartChance;
  stop_chance?: StopChance;
}
