/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * How important this behavior is. Lower priority behaviors will be executed first.
 */
export type Priority = number;
/**
 * The range of time in seconds the mob will stay looking in a random direction before looking elsewhere
 */
export type LookTime = [] | [X] | [X, Y];
/**
 * The X component.
 */
export type X = number;
/**
 * The Y component.
 */
export type Y = number;
/**
 * The rightmost angle a mob can look at on the horizontal plane with respect to its initial facing direction.
 */
export type MaxAngleOfViewHorizontal = number;
/**
 * The leftmost angle a mob can look at on the horizontal plane with respect to its initial facing direction.
 */
export type MinAngleOfViewHorizontal = number;

/**
 * Allows the mob to randomly look around.
 */
export interface RandomLookAround {
  priority?: Priority;
  look_time?: LookTime;
  max_angle_of_view_horizontal?: MaxAngleOfViewHorizontal;
  min_angle_of_view_horizontal?: MinAngleOfViewHorizontal;
}
