/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * How important this behavior is. Lower priority behaviors will be executed first.
 */
export type Priority = number;
/**
 * Vertical offset from the liquid.
 */
export type LiquidYOffset = number;
/**
 * Displacement for how much the entity will move up in the vertical axis.
 */
export type RiseDelta = number;
/**
 * Displacement for how much the entity will move down in the vertical axis.
 */
export type SinkDelta = number;

/**
 * Allows the mob to stay at a certain level when in liquid.
 */
export interface RiseToLiquidLevel {
  priority?: Priority;
  liquid_y_offset?: LiquidYOffset;
  rise_delta?: RiseDelta;
  sink_delta?: SinkDelta;
}
