/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * How important this behavior is. Lower priority behaviors will be executed first.
 */
export type Priority = number;
/**
 * The interval in which a sound will play when active in a 1/delay chance to kick off.
 */
export type SoundInterval = number;

/**
 * Allows the a mob to become scared when the weather outside is thundering.
 */
export interface Scared {
  priority?: Priority;
  sound_interval?: SoundInterval;
}
