/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * How important this behavior is. Lower priority behaviors will be executed first.
 */
export type Priority = number;
/**
 * Movement speed multiplier of the mob when using this AI Goal.
 */
export type SpeedMultiplier = number;
/**
 * Percent chance a slime or magma cube has to jump while in water / lava.
 */
export type JumpChancePercentage = number;

/**
 * Allow slimes to float in water / lava. Can only be used by Slime and Magma Cubes.
 */
export interface SlimeFloat {
  priority?: Priority;
  speed_multiplier?: SpeedMultiplier;
  jump_chance_percentage?: JumpChancePercentage;
}
