/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * How important this behavior is. Lower priority behaviors will be executed first.
 */
export type Priority = number;
/**
 * Movement speed multiplier of the mob when using this AI Goal.
 */
export type SpeedMultiplier = number;
/**
 * Allows the actor to be set to persist upon targeting a player.
 */
export type SetPersistent = boolean;
/**
 * Maximum rotation (in degrees), on the X-axis, this entity can rotate while trying to look at the target.
 */
export type XMaxRotation = number;
/**
 * Maximum rotation (in degrees), on the Y-axis, this entity can rotate while trying to look at the target.
 */
export type YMaxRotation = number;

/**
 * Can only be used by Slimes and Magma Cubes. Allows the mob to use a melee attack like the slime's.
 */
export interface SlimeAttack {
  priority?: Priority;
  speed_multiplier?: SpeedMultiplier;
  set_persistent?: SetPersistent;
  x_max_rotation?: XMaxRotation;
  y_max_rotation?: YMaxRotation;
}
