/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * How important this behavior is. Lower priority behaviors will be executed first.
 */
export type Priority = number;

/**
 * Allows the squid to move away from ground blocks and back to water. Can only be used by the Squid.
 */
export interface SquidMoveAwayFromGround {
  priority?: Priority;
}
