/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * How important this behavior is. Lower priority behaviors will be executed first.
 */
export type Priority = number;
/**
 * This mob starts swelling when a target is at least this many blocks away.
 */
export type StartDistance = number;
/**
 * This mob stops swelling when a target has moved away at least this many blocks.
 */
export type StopDistance = number;

/**
 * Allows the creeper to swell up when a player is nearby. It can only be used by Creepers.
 */
export interface Swell {
  priority?: Priority;
  start_distance?: StartDistance;
  stop_distance?: StopDistance;
}
