/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * How important this behavior is. Lower priority behaviors will be executed first.
 */
export type Priority = number;
/**
 * Movement speed multiplier of the mob when using this AI Goal.
 */
export type SpeedMultiplier = number;
/**
 * Percent chance to start wandering, when not path-finding. 1 = 100%
 */
export type Interval = number;
/**
 * Distance to look ahead for obstacle avoidance, while wandering.
 */
export type LookAhead = number;
/**
 * Amount of time (in seconds) to wander after wandering behavior was successfully started.
 */
export type WanderTime = number;

/**
 * Has the fish swim around when they can't pathfind.
 */
export interface SwimWander {
  priority?: Priority;
  speed_multiplier?: SpeedMultiplier;
  interval?: Interval;
  look_ahead?: LookAhead;
  wander_time?: WanderTime;
}
