/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * How important this behavior is. Lower priority behaviors will be executed first.
 */
export type Priority = number;
/**
 * Amount of time (in seconds) to stay idle.
 */
export type IdleTime = number;
/**
 * Percent chance this entity will go idle, 1.0 = 100%.
 */
export type SuccesRate = number;

/**
 * Allows the entity go idle, if swimming. Entity must be in water.
 */
export interface SwimIdle {
  priority?: Priority;
  idle_time?: IdleTime;
  success_rate?: SuccesRate;
}
