/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The IDs of the controls that will be created by the factory.
 */
export type ControlIDs =
  | string
  | {
      [k: string]: ControlID;
    };
export type ControlID = string;
