/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * If true, the element will be destroyed at the end of the animation.
 */
export type DestroyAtEnd =
  | ("popup" | "details_bubble_control" | "bundle_mode_popup_control" | "selected_item_details")
  | Variable;
/**
 * A variable is a reference to a value that can be used in the UI.
 */
export type Variable = Variable1 & Variable2;
export type Variable1 = string;
export type Variable2 = string;
