/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The type of the element
 */
export type Type =
  | "always_rotate"
  | "button"
  | "carousel_label"
  | "custom"
  | "dropdown"
  | "edit_box"
  | "grid"
  | "image_cycler"
  | "image"
  | "input_panel"
  | "label_cycler"
  | "label"
  | "panel"
  | "screen"
  | "scroll_track"
  | "scroll_view"
  | "scrollbar_box"
  | "slider_box"
  | "slider"
  | "stack_panel"
  | "toggle";
