/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The name of this feature in the form `namespace_name:feature_name`. `feature_name` must match the filename.
 */
export type Identifier = string;
export type BaseBlock = BlockIdentifier | BlockIdentifier1[];
/**
 * A minecraft block identifier.
 */
export type BlockIdentifier = string;
/**
 * A minecraft block identifier.
 */
export type BlockIdentifier1 = string;
/**
 * UNDOCUMENTED.
 */
export type MayReplace = BlockIdentifier[];
/**
 * UNDOCUMENTED.
 */
export type NumClusters = number;
/**
 * UNDOCUMENTED.
 */
export type ClustersRadius = number;
/**
 * UNDOCUMENTED.
 */
export type MayGrowOn = BlockIdentifier[];
/**
 * UNDOCUMENTED.
 */
export type MayGrowOn1 = BlockIdentifier[];
/**
 * UNDOCUMENTED.
 */
export type MayGrowOn2 = BlockIdentifier[];
/**
 * UNDOCUMENTED.
 */
export type TrunkWidth = number;
/**
 * UNDOCUMENTED.
 */
export type Base = number;
/**
 * UNDOCUMENTED.
 *
 * @minItems 1
 */
export type Intervals = [number, ...number[]];
/**
 * UNDOCUMENTED.
 */
export type MinimumHeightForCanopy = number;
/**
 * A minecraft block identifier.
 */
export type BlockIdentifier2 = string;
/**
 * UNDOCUMENTED.
 */
export type BranchLength = number;
/**
 * UNDOCUMENTED.
 */
export type BranchPosition = number;
/**
 * UNDOCUMENTED.
 */
export type Numerator = number;
/**
 * UNDOCUMENTED.
 */
export type Denominator = number;
/**
 * UNDOCUMENTED.
 */
export type CanopySize = number;
/**
 * UNDOCUMENTED.
 */
export type LeafBlock = string;
/**
 * UNDOCUMENTED.
 */
export type SimplifyCanopy = boolean;
/**
 * UNDOCUMENTED.
 */
export type Min = number;
/**
 * UNDOCUMENTED.
 */
export type Max = number;
/**
 * UNDOCUMENTED.
 */
export type MinWidth = number;
/**
 * UNDOCUMENTED.
 */
export type Rise = number;
/**
 * UNDOCUMENTED.
 */
export type Run = number;
/**
 * UNDOCUMENTED.
 */
export type VariationChance = ChanceInformation1 | number;
/**
 * UNDOCUMENTED.
 */
export type LeafBlock1 = string;
/**
 * UNDOCUMENTED.
 */
export type DecorationBlock = string;
/**
 * UNDOCUMENTED.
 */
export type NumSteps = number;
/**
 * UNDOCUMENTED.
 */
export type StepDirection = "down" | "up" | "out" | "away";
/**
 * UNDOCUMENTED.
 */
export type Height = number;
/**
 * UNDOCUMENTED.
 */
export type Radius = number;
/**
 * UNDOCUMENTED.
 */
export type LeafBlock2 = string;
/**
 * UNDOCUMENTED.
 */
export type CanopyHeight = number;
/**
 * UNDOCUMENTED.
 */
export type BaseRadius = number;
/**
 * UNDOCUMENTED.
 */
export type CoreWidth = number;
/**
 * UNDOCUMENTED.
 */
export type SimplifyCanopy1 = boolean;
/**
 * UNDOCUMENTED.
 */
export type LeafBlock3 = string;
/**
 * UNDOCUMENTED.
 */
export type CanopyHeight1 = number;
/**
 * UNDOCUMENTED.
 */
export type BaseRadius1 = number;
/**
 * UNDOCUMENTED.
 */
export type RadiusStepModifier = number;
/**
 * UNDOCUMENTED.
 */
export type CoreWidth1 = number;
/**
 * UNDOCUMENTED.
 */
export type LeafBlock4 = string;
/**
 * UNDOCUMENTED.
 */
export type CanopyHeight2 = number;
/**
 * UNDOCUMENTED.
 */
export type BaseRadius2 = number;
/**
 * UNDOCUMENTED.
 */
export type LeafBlock5 = string;
/**
 * UNDOCUMENTED.
 */
export type CanopyHeight3 = number;
/**
 * UNDOCUMENTED.
 */
export type CoreWidth2 = number;
/**
 * UNDOCUMENTED.
 */
export type OuterRadius = number;
/**
 * UNDOCUMENTED.
 */
export type InnerRadius = number;
/**
 * UNDOCUMENTED.
 */
export type LeafBlock6 = string;
/**
 * UNDOCUMENTED.
 */
export type LowerOffset = number;
/**
 * UNDOCUMENTED.
 */
export type UpperOffset = number;
/**
 * UNDOCUMENTED.
 */
export type MaxRadius = number;
/**
 * UNDOCUMENTED.
 */
export type LeafBlock7 = string;
/**
 * A minecraft block identifier.
 */
export type BlockIdentifier3 = string;
/**
 * UNDOCUMENTED.
 */
export type NumSteps1 = number;
/**
 * UNDOCUMENTED.
 */
export type StepDirection1 = "down" | "up" | "out" | "away";
/**
 * UNDOCUMENTED.
 */
export type LogLength = number;
/**
 * UNDOCUMENTED.
 */
export type StumpHeight = number;
/**
 * UNDOCUMENTED.
 */
export type HeightModifier = number;
/**
 * A minecraft block identifier.
 */
export type BlockIdentifier4 = string;
/**
 * UNDOCUMENTED.
 */
export type LogDecorationFeature = string;
/**
 * A minecraft block identifier.
 */
export type BlockIdentifier5 = string;
/**
 * UNDOCUMENTED.
 */
export type NumSteps2 = number;
/**
 * UNDOCUMENTED.
 */
export type StepDirection2 = "down" | "up" | "out" | "away";
/**
 * UNDOCUMENTED.
 */
export type Base1 = number;
/**
 * UNDOCUMENTED.
 */
export type Variance = number;
/**
 * UNDOCUMENTED.
 */
export type Scale = number;
/**
 * UNDOCUMENTED.
 */
export type TrunkWidth1 = number;
/**
 * UNDOCUMENTED.
 */
export type Slope = number;
/**
 * UNDOCUMENTED.
 */
export type Density = number;
/**
 * UNDOCUMENTED.
 */
export type MinAltitudeFactor = number;
/**
 * A minecraft block identifier.
 */
export type BlockIdentifier6 = string;
/**
 * UNDOCUMENTED.
 */
export type WidthScale = number;
/**
 * UNDOCUMENTED.
 */
export type FoliageAltitudeFactor = number;
/**
 * UNDOCUMENTED.
 */
export type TrunkWidth2 = number;
/**
 * UNDOCUMENTED.
 */
export type Base2 = number;
/**
 * UNDOCUMENTED.
 */
export type Items = number;
/**
 * UNDOCUMENTED.
 */
export type Intervals1 = Items[];
/**
 * A minecraft block identifier.
 */
export type BlockIdentifier7 = string;
/**
 * A minecraft block identifier.
 */
export type BlockIdentifier8 = string;
/**
 * UNDOCUMENTED.
 */
export type NumSteps3 = number;
/**
 * UNDOCUMENTED.
 */
export type StepDirection3 = "down" | "up" | "out" | "away";
/**
 * UNDOCUMENTED.
 */
export type BranchLength1 = number;
/**
 * UNDOCUMENTED.
 */
export type BranchSlope = number;
/**
 * UNDOCUMENTED.
 */
export type Min1 = number;
/**
 * UNDOCUMENTED.
 */
export type Max1 = number;
/**
 * UNDOCUMENTED.
 */
export type TrunkHeight3 = number;
/**
 * UNDOCUMENTED.
 */
export type HeightModifier1 = number;
/**
 * UNDOCUMENTED.
 */
export type CanBeSubmerged =
  | {
      max_depth?: MaxDepth;
    }
  | CanBeSubmerged1;
/**
 * UNDOCUMENTED.
 */
export type MaxDepth = number;
/**
 * UNDOCUMENTED.
 */
export type CanBeSubmerged1 = boolean;
/**
 * A minecraft block identifier.
 */
export type BlockIdentifier9 = string;
/**
 * A minecraft block identifier.
 */
export type BlockIdentifier10 = string;
/**
 * UNDOCUMENTED.
 */
export type NumSteps4 = number;
/**
 * UNDOCUMENTED.
 */
export type StepDirection4 = "down" | "up" | "out" | "away";
/**
 * UNDOCUMENTED.
 */
export type CanopySize1 = number;
/**
 * A minecraft block identifier.
 */
export type BlockIdentifier11 = string;
/**
 * UNDOCUMENTED.
 */
export type SimplifyCanopy2 = boolean;
/**
 * UNDOCUMENTED.
 */
export type Min2 = number;
/**
 * UNDOCUMENTED.
 */
export type Max2 = number;
/**
 * UNDOCUMENTED.
 */
export type MinWidth1 = number;
/**
 * UNDOCUMENTED.
 */
export type Rise1 = number;
/**
 * UNDOCUMENTED.
 */
export type Run1 = number;
/**
 * UNDOCUMENTED.
 */
export type VariationChance1 = ChanceInformation1 | number;
/**
 * A minecraft block identifier.
 */
export type BlockIdentifier12 = string;
/**
 * A minecraft block identifier.
 */
export type BlockIdentifier13 = string;
/**
 * UNDOCUMENTED.
 */
export type NumSteps5 = number;
/**
 * UNDOCUMENTED.
 */
export type StepDirection5 = "down" | "up" | "out" | "away";
/**
 * UNDOCUMENTED.
 */
export type Height1 = number;
/**
 * UNDOCUMENTED.
 */
export type Radius1 = number;
/**
 * A minecraft block identifier.
 */
export type BlockIdentifier14 = string;
/**
 * UNDOCUMENTED.
 */
export type CanopyHeight4 = number;
/**
 * UNDOCUMENTED.
 */
export type BaseRadius3 = number;
/**
 * UNDOCUMENTED.
 */
export type CoreWidth3 = number;
/**
 * UNDOCUMENTED.
 */
export type SimplifyCanopy3 = boolean;
/**
 * A minecraft block identifier.
 */
export type BlockIdentifier15 = string;
/**
 * UNDOCUMENTED.
 */
export type CanopyHeight5 = number;
/**
 * UNDOCUMENTED.
 */
export type BaseRadius4 = number;
/**
 * UNDOCUMENTED.
 */
export type RadiusStepModifier1 = number;
/**
 * UNDOCUMENTED.
 */
export type CoreWidth4 = number;
/**
 * A minecraft block identifier.
 */
export type BlockIdentifier16 = string;
/**
 * UNDOCUMENTED.
 */
export type CanopyHeight6 = number;
/**
 * UNDOCUMENTED.
 */
export type BaseRadius5 = number;
/**
 * A minecraft block identifier.
 */
export type BlockIdentifier17 = string;
/**
 * UNDOCUMENTED.
 */
export type CanopyHeight7 = number;
/**
 * UNDOCUMENTED.
 */
export type CoreWidth5 = number;
/**
 * UNDOCUMENTED.
 */
export type OuterRadius1 = number;
/**
 * UNDOCUMENTED.
 */
export type InnerRadius1 = number;
/**
 * A minecraft block identifier.
 */
export type BlockIdentifier18 = string;
/**
 * UNDOCUMENTED.
 */
export type LowerOffset1 = number;
/**
 * UNDOCUMENTED.
 */
export type UpperOffset1 = number;
/**
 * UNDOCUMENTED.
 */
export type MaxRadius1 = number;
/**
 * A minecraft block identifier.
 */
export type BlockIdentifier19 = string;
/**
 * UNDOCUMENTED.
 */
export type CanopyHeight8 = number;
/**
 * UNDOCUMENTED.
 */
export type CanopyRadius = number;
/**
 * UNDOCUMENTED.
 */
export type LeafPlacementAttempts = number;
/**
 * UNDOCUMENTED.
 */
export type Items1 = [] | [number] | [number, number];
/**
 * UNDOCUMENTED.
 */
export type LeafBlocks = Items1[];

/**
 * Feature type 'minecraft:tree_feature' has not yet been documented.
 */
export interface StructureTemplateFeature {
  description: Description;
  base_block?: BaseBlock;
  base_cluster?: BaseCluster;
  may_grow_on?: MayGrowOn;
  may_replace?: MayGrowOn1;
  may_grow_through?: MayGrowOn2;
  acacia_trunk?: AcaciaTrunk;
  fallen_trunk?: FallenTrunk;
  fancy_trunk?: FancyTrunk;
  mega_trunk?: MegaTrunk;
  trunk?: Trunk;
  acacia_canopy?: AcaciaCanopy1;
  canopy?: Canopy1;
  fancy_canopy?: FancyCanopy1;
  mega_canopy?: MegaCanopy1;
  mega_pine_canopy?: MegaPineCanopy1;
  pine_canopy?: PineCanopy1;
  roofed_canopy?: RoofedCanopy1;
  spruce_canopy?: SpruceCanopy1;
  random_spread_canopy?: RandomSpreadCanopy;
}
/**
 * UNDOCUMENTED.
 */
export interface Description {
  identifier: Identifier;
  [k: string]: unknown;
}
/**
 * UNDOCUMENTED.
 */
export interface BaseCluster {
  may_replace: MayReplace;
  num_clusters: NumClusters;
  cluster_radius: ClustersRadius;
}
/**
 * UNDOCUMENTED.
 */
export interface AcaciaTrunk {
  trunk_width?: TrunkWidth;
  trunk_height?: TrunkHeight;
  trunk_lean?: {
    [k: string]: unknown;
  };
  trunk_block?: BlockIdentifier2;
  branches?: Branches;
}
/**
 * UNDOCUMENTED.
 */
export interface TrunkHeight {
  base?: Base;
  intervals?: Intervals;
  min_height_for_canopy?: MinimumHeightForCanopy;
}
/**
 * UNDOCUMENTED.
 */
export interface Branches {
  branch_length?: BranchLength;
  branch_position?: BranchPosition;
  branch_chance?: ChanceInformation;
  branch_canopy?: BranchCanopy;
  trunk_decoration?: TrunkDecoration;
}
/**
 * UNDOCUMENTED.
 */
export interface ChanceInformation {
  numerator?: Numerator;
  denominator?: Denominator;
}
/**
 * UNDOCUMENTED.
 */
export interface BranchCanopy {
  acacia_canopy?: AcaciaCanopy;
  canopy?: Canopy;
  fancy_canopy?: FancyCanopy;
  mega_canopy?: MegaCanopy;
  mega_pine_canopy?: MegaPineCanopy;
  pine_canopy?: PineCanopy;
  roofed_canopy?: RoofedCanopy;
  spruce_canopy?: SpruceCanopy;
}
/**
 * UNDOCUMENTED.
 */
export interface AcaciaCanopy {
  canopy_size?: CanopySize;
  leaf_block?: LeafBlock;
  simplify_canopy?: SimplifyCanopy;
}
/**
 * UNDOCUMENTED.
 */
export interface Canopy {
  canopy_offset?: CanopyOffset;
  min_width?: MinWidth;
  canopy_slope?: CanopySlope;
  variation_chance?: VariationChance;
  leaf_block?: LeafBlock1;
  canopy_decoration?: CanopyDecoration;
}
/**
 * UNDOCUMENTED.
 */
export interface CanopyOffset {
  min?: Min;
  max?: Max;
}
/**
 * UNDOCUMENTED.
 */
export interface CanopySlope {
  rise?: Rise;
  run?: Run;
}
/**
 * UNDOCUMENTED.
 */
export interface ChanceInformation1 {
  numerator?: Numerator;
  denominator?: Denominator;
}
/**
 * UNDOCUMENTED.
 */
export interface CanopyDecoration {
  decoration_chance?: ChanceInformation2;
  decoration_block?: DecorationBlock;
  num_steps?: NumSteps;
  step_direction?: StepDirection;
}
/**
 * UNDOCUMENTED.
 */
export interface ChanceInformation2 {
  numerator?: Numerator;
  denominator?: Denominator;
}
/**
 * UNDOCUMENTED.
 */
export interface FancyCanopy {
  height?: Height;
  radius?: Radius;
  leaf_block?: LeafBlock2;
}
/**
 * UNDOCUMENTED.
 */
export interface MegaCanopy {
  canopy_height?: CanopyHeight;
  base_radius?: BaseRadius;
  core_width?: CoreWidth;
  simplify_canopy?: SimplifyCanopy1;
  leaf_block?: LeafBlock3;
}
/**
 * UNDOCUMENTED.
 */
export interface MegaPineCanopy {
  canopy_height?: CanopyHeight1;
  base_radius?: BaseRadius1;
  radius_step_modifier?: RadiusStepModifier;
  core_width?: CoreWidth1;
  leaf_block?: LeafBlock4;
}
/**
 * UNDOCUMENTED.
 */
export interface PineCanopy {
  canopy_height?: CanopyHeight2;
  base_radius?: BaseRadius2;
  leaf_block?: LeafBlock5;
}
/**
 * UNDOCUMENTED.
 */
export interface RoofedCanopy {
  canopy_height?: CanopyHeight3;
  core_width?: CoreWidth2;
  outer_radius?: OuterRadius;
  inner_radius?: InnerRadius;
  leaf_block?: LeafBlock6;
}
/**
 * UNDOCUMENTED.
 */
export interface SpruceCanopy {
  lower_offset?: LowerOffset;
  upper_offset?: UpperOffset;
  max_radius?: MaxRadius;
  leaf_block?: LeafBlock7;
}
/**
 * UNDOCUMENTED.
 */
export interface TrunkDecoration {
  decoration_chance?: ChanceInformation3;
  decoration_block?: BlockIdentifier3;
  num_steps?: NumSteps1;
  step_direction?: StepDirection1;
}
/**
 * UNDOCUMENTED.
 */
export interface ChanceInformation3 {
  numerator?: Numerator;
  denominator?: Denominator;
}
/**
 * UNDOCUMENTED.
 */
export interface FallenTrunk {
  log_length?: LogLength;
  stump_height?: StumpHeight;
  height_modifier?: HeightModifier;
  trunk_block?: BlockIdentifier4;
  log_decoration_feature?: LogDecorationFeature;
  trunk_decoration?: TrunkDecoration1;
}
/**
 * UNDOCUMENTED.
 */
export interface TrunkDecoration1 {
  decoration_chance?: ChanceInformation4;
  decoration_block?: BlockIdentifier5;
  num_steps?: NumSteps2;
  step_direction?: StepDirection2;
}
/**
 * UNDOCUMENTED.
 */
export interface ChanceInformation4 {
  numerator?: Numerator;
  denominator?: Denominator;
}
/**
 * UNDOCUMENTED.
 */
export interface FancyTrunk {
  trunk_height?: TrunkHeight1;
  trunk_width?: TrunkWidth1;
  branches?: Branches1;
  trunk_block?: BlockIdentifier6;
  width_scale?: WidthScale;
  foliage_altitude_factor?: FoliageAltitudeFactor;
}
/**
 * UNDOCUMENTED.
 */
export interface TrunkHeight1 {
  base?: Base1;
  variance?: Variance;
  scale?: Scale;
}
/**
 * UNDOCUMENTED.
 */
export interface Branches1 {
  slope?: Slope;
  density?: Density;
  min_altitude_factor?: MinAltitudeFactor;
}
/**
 * UNDOCUMENTED.
 */
export interface MegaTrunk {
  trunk_width?: TrunkWidth2;
  trunk_height?: TrunkHeight2;
  trunk_block?: BlockIdentifier7;
  trunk_decoration?: TrunkDecoration2;
  branches?: Branches2;
}
/**
 * UNDOCUMENTED.
 */
export interface TrunkHeight2 {
  base?: Base2;
  intervals?: Intervals1;
}
/**
 * UNDOCUMENTED.
 */
export interface TrunkDecoration2 {
  decoration_chance?: ChanceInformation5;
  decoration_block?: BlockIdentifier8;
  num_steps?: NumSteps3;
  step_direction?: StepDirection3;
}
/**
 * UNDOCUMENTED.
 */
export interface ChanceInformation5 {
  numerator?: Numerator;
  denominator?: Denominator;
}
/**
 * UNDOCUMENTED.
 */
export interface Branches2 {
  branch_length?: BranchLength1;
  branch_slope?: BranchSlope;
  /**
   * UNDOCUMENTED.
   */
  branch_interval?: number;
  branch_altitude_factor?: BranchAltitudeFactor;
  branch_canopy?: BranchCanopy1;
}
/**
 * UNDOCUMENTED.
 */
export interface BranchAltitudeFactor {
  min?: Min1;
  max?: Max1;
}
/**
 * UNDOCUMENTED.
 */
export interface BranchCanopy1 {
  acacia_canopy?: AcaciaCanopy;
  canopy?: Canopy;
  fancy_canopy?: FancyCanopy;
  mega_canopy?: MegaCanopy;
  mega_pine_canopy?: MegaPineCanopy;
  pine_canopy?: PineCanopy;
  roofed_canopy?: RoofedCanopy;
  spruce_canopy?: SpruceCanopy;
}
/**
 * UNDOCUMENTED.
 */
export interface Trunk {
  trunk_height?: TrunkHeight3;
  height_modifier?: HeightModifier1;
  can_be_submerged?: CanBeSubmerged;
  trunk_block?: BlockIdentifier9;
  trunk_decoration?: TrunkDecoration3;
}
/**
 * UNDOCUMENTED.
 */
export interface TrunkDecoration3 {
  decoration_chance?: ChanceInformation6;
  decoration_block?: BlockIdentifier10;
  num_steps?: NumSteps4;
  step_direction?: StepDirection4;
}
/**
 * UNDOCUMENTED.
 */
export interface ChanceInformation6 {
  numerator?: Numerator;
  denominator?: Denominator;
}
/**
 * UNDOCUMENTED.
 */
export interface AcaciaCanopy1 {
  canopy_size?: CanopySize1;
  leaf_block?: BlockIdentifier11;
  simplify_canopy?: SimplifyCanopy2;
}
/**
 * UNDOCUMENTED.
 */
export interface Canopy1 {
  canopy_offset?: CanopyOffset1;
  min_width?: MinWidth1;
  canopy_slope?: CanopySlope1;
  variation_chance?: VariationChance1;
  leaf_block?: BlockIdentifier12;
  canopy_decoration?: CanopyDecoration1;
}
/**
 * UNDOCUMENTED.
 */
export interface CanopyOffset1 {
  min?: Min2;
  max?: Max2;
}
/**
 * UNDOCUMENTED.
 */
export interface CanopySlope1 {
  rise?: Rise1;
  run?: Run1;
}
/**
 * UNDOCUMENTED.
 */
export interface CanopyDecoration1 {
  decoration_chance?: ChanceInformation7;
  decoration_block?: BlockIdentifier13;
  num_steps?: NumSteps5;
  step_direction?: StepDirection5;
}
/**
 * UNDOCUMENTED.
 */
export interface ChanceInformation7 {
  numerator?: Numerator;
  denominator?: Denominator;
}
/**
 * UNDOCUMENTED.
 */
export interface FancyCanopy1 {
  height?: Height1;
  radius?: Radius1;
  leaf_block?: BlockIdentifier14;
}
/**
 * UNDOCUMENTED.
 */
export interface MegaCanopy1 {
  canopy_height?: CanopyHeight4;
  base_radius?: BaseRadius3;
  core_width?: CoreWidth3;
  simplify_canopy?: SimplifyCanopy3;
  leaf_block?: BlockIdentifier15;
}
/**
 * UNDOCUMENTED.
 */
export interface MegaPineCanopy1 {
  canopy_height?: CanopyHeight5;
  base_radius?: BaseRadius4;
  radius_step_modifier?: RadiusStepModifier1;
  core_width?: CoreWidth4;
  leaf_block?: BlockIdentifier16;
}
/**
 * UNDOCUMENTED.
 */
export interface PineCanopy1 {
  canopy_height?: CanopyHeight6;
  base_radius?: BaseRadius5;
  leaf_block?: BlockIdentifier17;
}
/**
 * UNDOCUMENTED.
 */
export interface RoofedCanopy1 {
  canopy_height?: CanopyHeight7;
  core_width?: CoreWidth5;
  outer_radius?: OuterRadius1;
  inner_radius?: InnerRadius1;
  leaf_block?: BlockIdentifier18;
}
/**
 * UNDOCUMENTED.
 */
export interface SpruceCanopy1 {
  lower_offset?: LowerOffset1;
  upper_offset?: UpperOffset1;
  max_radius?: MaxRadius1;
  leaf_block?: BlockIdentifier19;
}
/**
 * UNDOCUMENTED.
 */
export interface RandomSpreadCanopy {
  canopy_height?: CanopyHeight8;
  canopy_radius?: CanopyRadius;
  leaf_placement_attempts?: LeafPlacementAttempts;
  leaf_blocks?: LeafBlocks;
}
