/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The name of this feature in the form `namespace_name:feature_name`. `feature_name` must match the filename.
 */
export type Identifier = string;
/**
 * A minecraft block identifier.
 */
export type ReplaceBlock = string;
/**
 * UNDOCUMENTED.
 */
export type ReplaceableBlocks = ReplaceBlock[];
/**
 * UNDOCUMENTED.
 */
export type GroundBlock = string;
/**
 * UNDOCUMENTED.
 */
export type VegetationFeature = string;
/**
 * UNDOCUMENTED.
 */
export type Surface = string;
/**
 * UNDOCUMENTED.
 */
export type Depth = number;
/**
 * UNDOCUMENTED.
 */
export type ExtraDeepBlockChance = number;
/**
 * UNDOCUMENTED.
 */
export type VerticalRange = number;
/**
 * UNDOCUMENTED.
 */
export type VegatationChance = number;
/**
 * UNDOCUMENTED.
 */
export type HorizontalRadius = number;
/**
 * UNDOCUMENTED.
 */
export type ExtraEgdeColumnChance = number;
/**
 * UNDOCUMENTED.
 */
export type Waterlogged = boolean;

/**
 * Feature type `minecraft:vegetation_patch_feature` has not yet been documented.
 */
export interface VegetationPatchFeature {
  description: Description;
  replaceable_blocks?: ReplaceableBlocks;
  ground_block?: GroundBlock;
  vegetation_feature?: VegetationFeature;
  surface?: Surface;
  depth?: Depth;
  extra_deep_block_chance?: ExtraDeepBlockChance;
  vertical_range?: VerticalRange;
  vegetation_chance?: VegatationChance;
  horizontal_radius?: HorizontalRadius;
  extra_edge_column_chance?: ExtraEgdeColumnChance;
  waterlogged?: Waterlogged;
}
/**
 * UNDOCUMENTED.
 */
export interface Description {
  identifier: Identifier;
  [k: string]: unknown;
}
