/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The name of this feature in the form `namespace_name:feature_name`. `feature_name` must match the filename.
 */
export type Identifier = string;
/**
 * Age of the head of the plant.
 */
export type Age = number | Range;
/**
 * The maximum plant height.
 */
export type RangeMax = number;
/**
 * The minimum plant height.
 */
export type RangeMin = number;
/**
 * Collection of weighted heights that placement will select from.
 *
 * @minItems 1
 */
export type HeightDistribution = [HeightDistribution1, ...HeightDistribution1[]];
/**
 * Collection of weighted heights that placement will select from.
 *
 * @minItems 2
 * @maxItems 2
 */
export type HeightDistribution1 = [PlantHeight, Weight];
/**
 * Plant height.
 */
export type PlantHeight = number | Range;
/**
 * Weight used in random selection. Value is relative to other weights in the collection.
 */
export type Weight = number;
/**
 * Direction that the plant grows towards. Valid values: UP and DOWN
 */
export type GrowthDirection = "UP" | "DOWN" | "up" | "down";
/**
 * Collection of weighted block descriptor that placement will select from for the body of the plant.
 *
 * @minItems 1
 */
export type BodyBlocks = [Blocks, ...Blocks[]];
/**
 * Collection of weighted block descriptor that placement will select from for the plant.
 *
 * @minItems 2
 * @maxItems 2
 */
export type Blocks = [PlantBodyBlock, Weight1];
/**
 * Plant body block.
 */
export type PlantBodyBlock = string;
/**
 * Weight used in random selection. Value is relative to other weights in the collection.
 */
export type Weight1 = number;
/**
 * Collection of weighted block descriptor that placement will select from for the body of the plant.
 *
 * @minItems 1
 */
export type HeadBlocks = [Blocks, ...Blocks[]];
/**
 * Plant blocks can be placed in water.
 */
export type AllowWater = boolean;

/**
 * `minecraft:growing_plant_feature` places a growing plant in the world. A growing plant is a column that is anchored either to the ceiling or the floor, based on its growth direction.
 * The growing plant has a body and a head, where the head is the tip of the plant, and the body consists of the remainder blocks.
 * This feature can be used to define growing plants with variable body and head blocks, e.g. Cave Vines.
 */
export interface GrowingPlantFeature {
  description: Description;
  age?: Age;
  height_distribution: HeightDistribution;
  growth_direction: GrowthDirection;
  body_blocks: BodyBlocks;
  head_blocks: HeadBlocks;
  allow_water?: AllowWater;
}
/**
 * UNDOCUMENTED.
 */
export interface Description {
  identifier: Identifier;
  [k: string]: unknown;
}
/**
 * A range.
 */
export interface Range {
  range_max: RangeMax;
  range_min: RangeMin;
  [k: string]: unknown;
}
