/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The name of this feature in the form `namespace_name:feature_name`. `feature_name` must match the filename.
 */
export type Identifier = string;
/**
 * Named reference of feature to be placed.
 */
export type ScanSurfaceFeature = string;

/**
 * `minecraft:scan_surface` scans the surface of a Chunk, calling place() on the surface of each block column.
 * Succeeds if: A Feature was successfully placed during the scan.
 * Fails if: No Feature was placed during the course of the scan.
 */
export interface RectLayout {
  description: Description;
  scan_surface_feature: ScanSurfaceFeature;
}
/**
 * UNDOCUMENTED.
 */
export interface Description {
  identifier: Identifier;
  [k: string]: unknown;
}
