/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The amplifier for the mob effect.
 */
export type Amplifier = number;
/**
 * The duration of the mob effect.
 */
export type Duration = number;
/**
 * The mob effect to apply.
 */
export type Effect = string;
/**
 * The target context to execute against.
 */
export type Target = string;

/**
 * Apply mob effect to target.
 */
export interface AddMobEffect {
  amplifier?: Amplifier;
  duration?: Duration;
  effect?: Effect;
  target?: Target;
}
