/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The target context to execute against.
 */
export type Target = string;

/**
 * Kill target. If target is self and this is run from a block then destroy the block.
 */
export interface Die {
  target?: Target;
}
