/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * File path, relative to the Behavior Pack's path, to the loot table file.
 */
export type Table = string;

/**
 * Spawn loot from block.
 */
export interface SpawnLoot {
  table: Table;
}
